barres <-
function() {
  tkwm.withdraw(Env$Fen4)
  Fen8=tktoplevel()
  tktitle(Fen8)="GrapheR"
  tkwm.resizable(Fen8,FALSE,FALSE)
  tcl("wm","protocol",Fen8,"WM_DELETE_WINDOW",function() {if (Env$toolbar.GrapheR==1) {tkdestroy(Env$Toolbar);assign("toolbar.GrapheR",0,pos=Env)};tkdestroy(Fen8);tkdestroy(Env$Fen4);tkdestroy(Env$Fen1)})
  frametot=tkframe(Fen8)
  frame0=tkframe(frametot)
  tkgrid(tklabel(frame0,image=tkimage.create("photo",file=file.path(.path.package("GrapheR"),"images",Env$images[11,1],fsep=.Platform$file.sep)),width=800,height=40))
  tkpack(frame0)
  frame1=tkframe(frametot)																	# Fenêtre 8 - frame 1 : généralités
  assign("niv.prop","",pos=Env)
  assign("col.str1","white",pos=Env)
  assign("col.str2","black",pos=Env)
  assign("dens.motif",0,pos=Env)
  assign("ang.motif",0,pos=Env)
  assign("col.motif","black",pos=Env)
  assign("legende.titre","",pos=Env)
  varValue=tclVar()
  var.choose=ttkcombobox(frame1,font=Env$police,values=names(Env$datas.GrapheR),textvariable=varValue,state="readonly")
  tkbind(var.choose,"<<ComboboxSelected>>",function() {barres.var(varValue=varValue,fact2Value=fact2Value,typeValue=typeValue,fact2.lab=fact2.lab,fact2.choose=fact2.choose,rb1=rb1,rb2=rb2,rb3=rb3,prop.but=prop.but,erreur.choose=erreur.choose,
    legende.lab=legende.lab,legende.check=legende.check,nom.legende.lab=nom.legende.lab,nom.legende.but=nom.legende.but,legende.pos.lab=legende.pos.lab,legende.pos.choose=legende.pos.choose)})
  fact1Value=tclVar()
  fact1.choose=ttkcombobox(frame1,font=Env$police,values=names(Env$datas.GrapheR[which(Env$variables=="F")]),textvariable=fact1Value,state="readonly")
  tkbind(fact1.choose,"<<ComboboxSelected>>",function() {barres.fact1(fact1Value=fact1Value)})
  fact2.lab=tklabel(frame1,text=Env$vocab[106,1],font=Env$police)
  fact2Value=tclVar()
  fact2.choose=ttkcombobox(frame1,font=Env$police,values=c(Env$vocab[48,1],names(Env$datas.GrapheR[which(Env$variables=="F")])),textvariable=fact2Value,state="readonly")
  tkbind(fact2.choose,"<<ComboboxSelected>>",function() {barres.fact2(fact2Value=fact2Value,besideValue=besideValue,typeValue=typeValue,legende.lab=legende.lab,legende.check=legende.check,nom.legende.lab=nom.legende.lab,nom.legende.but=nom.legende.but,
    legende.pos.lab=legende.pos.lab,legende.pos.choose=legende.pos.choose,erreur.lab=erreur.lab,erreur.choose=erreur.choose,col.erreur.lab=col.erreur.lab,col.erreur=col.erreur,col.erreur.choose=col.erreur.choose,
    segment.lab=segment.lab,segment.check=segment.check)})
  rb1=tkradiobutton(frame1,font=Env$police,command=function() {barres.type1(fact2.choose=fact2.choose,erreur.choose=erreur.choose,erreur.lab=erreur.lab,col.erreur.lab=col.erreur.lab,col.erreur=col.erreur,
    col.erreur.choose=col.erreur.choose,segment.lab=segment.lab,segment.check=segment.check)})
  rb2=tkradiobutton(frame1,font=Env$police,command=function() {barres.type2(fact2.choose=fact2.choose,besideValue=besideValue,erreur.choose=erreur.choose,erreur.lab=erreur.lab,col.erreur.lab=col.erreur.lab,col.erreur=col.erreur,
    col.erreur.choose=col.erreur.choose,segment.lab=segment.lab,segment.check=segment.check)})
  rb3=tkradiobutton(frame1,font=Env$police,command=function() {barres.type3(legende.lab=legende.lab,legende.check=legende.check,nom.legende.lab=nom.legende.lab,nom.legende.but=nom.legende.but,legende.pos.lab=legende.pos.lab,
    legende.pos.choose=legende.pos.choose,besideValue=besideValue,erreur.lab=erreur.lab,erreur.choose=erreur.choose,col.erreur.lab=col.erreur.lab,col.erreur=col.erreur,col.erreur.choose=col.erreur.choose,segment.lab=segment.lab,
    segment.check=segment.check)})
  typeValue=tclVar("moy")
  tkconfigure(rb1,variable=typeValue,value="som",text=Env$vocab[108,1])
  tkconfigure(rb2,variable=typeValue,value="moy",text=Env$vocab[109,1])
  tkconfigure(rb3,variable=typeValue,value="prop",text=Env$vocab[110,1])
  prop.but=tkbutton(frame1,text=Env$vocab[111,1],font=Env$police,width=16,command=function () {prop.barres(var=tclvalue(varValue),prop=Env$niv.prop,beside=as.numeric(tclvalue(besideValue)),erreur.lab=erreur.lab,
    erreur.choose=erreur.choose,col.erreur.lab=col.erreur.lab,col.erreur=col.erreur,col.erreur.choose=col.erreur.choose,segment.lab=segment.lab,segment.check=segment.check,legende.lab=legende.lab,
    legende.check=legende.check,nom.legende.lab=nom.legende.lab,nom.legende.but=nom.legende.but,legende.pos.lab=legende.pos.lab,legende.pos.choose=legende.pos.choose)})
  tkgrid(tklabel(frame1,text=Env$vocab[46,1],font=Env$police),row=0,column=1,sticky="e")
  tkgrid(var.choose,row=0,column=2)
  tkgrid(tklabel(frame1,text="                                        ",font=Env$police),row=0,column=3)
  tkgrid(tklabel(frame1,text=Env$vocab[107,1],font=Env$police),row=1,column=4,sticky="e")
  tkgrid(rb1,row=0,column=5,sticky="w")
  tkgrid(tklabel(frame1,text=Env$vocab[105,1],font=Env$police),row=1,column=1,sticky="e")
  tkgrid(fact1.choose,row=1,column=2,sticky="w")
  tkgrid(rb2,row=1,column=5,sticky="w")
  tkgrid(fact2.lab,row=2,column=1,sticky="e")
  tkgrid(fact2.choose,row=2,column=2,sticky="w")
  tkgrid(rb3,row=2,column=5,sticky="w")
  tkgrid(prop.but,row=2,column=6)
  tkpack(frame1)
  frame2=tkframe(frametot)
  tkgrid(tklabel(frame2,text=" ",font=tkfont.create(family="Arial",size=4)))
  tkgrid(tklabel(frame2,image=tkimage.create("photo",file=file.path(.path.package("GrapheR"),"images",Env$images[15,1],fsep=.Platform$file.sep)),width=800,height=21))
  tkpack(frame2)
  frame3=tkframe(frametot)																	# Fenêtre 8 - frame 3 : titre
  titreValue=tclVar("")
  titre=tkentry(frame3,width=30,font=Env$police,textvariable=titreValue)
  col.titre=tclVar("black")
  col.titre.choose=tkbutton(frame3,text="Aa",font=tkfont.create(family="Arial",size=10,weight="bold"),command=function() {couleur(fen=Fen8,titre=55,var=col.titre,widg=col.titre.choose,type="but",plusieurs=FALSE)})
  taille.titre=tclVar("1.5")
  taille.titre.choose=tkscale(frame3,from=0.5,to=4,showvalue=TRUE,font=Env$police,variable=taille.titre,resolution=0.1,orient="horizontal")
  tkgrid(tklabel(frame3,text=Env$vocab[54,1],font=Env$police),row=0,column=1)
  tkgrid(titre,row=0,column=2)
  tkgrid(tklabel(frame3,text="                             ",font=Env$police),row=0,column=3)
  tkgrid(tklabel(frame3,text=Env$vocab[56,1],font=Env$police),row=0,column=4)
  tkgrid(col.titre.choose,row=0,column=5)
  tkgrid(tklabel(frame3,text="                             ",font=Env$police),row=0,column=6)
  tkgrid(tklabel(frame3,text=Env$vocab[57,1],font=Env$police),row=0,column=7)
  tkgrid(taille.titre.choose,row=0,column=8)
  tkpack(frame3)
  frame4=tkframe(frametot)
  tkgrid(tklabel(frame4,text=" ",font=tkfont.create(family="Arial",size=4)))
  tkgrid(tklabel(frame4,image=tkimage.create("photo",file=file.path(.path.package("GrapheR"),"images",Env$images[16,1],fsep=.Platform$file.sep)),width=800,height=21))
  tkpack(frame4)
  frame5=tkframe(frametot)																	# Fenêtre 8 - frame 5 : axes
  col.axes=tclVar("black")
  col.axes.choose=tkbutton(frame5,text="Aa",font=tkfont.create(family="Arial",size=10,weight="bold"),command=function() {couleur(fen=Fen8,titre=87,var=col.axes,widg=col.axes.choose,type="but",plusieurs=FALSE)})
  col.legendes=tclVar("black")
  col.legendes.choose=tkbutton(frame5,text="Aa",font=tkfont.create(family="Arial",size=10,weight="bold"),command=function() {couleur(fen=Fen8,titre=62,var=col.legendes,widg=col.legendes.choose,type="but",plusieurs=FALSE)})
  taille.axes=tclVar("1")
  taille.axes.choose=tkscale(frame5,from=0.5,to=4,showvalue=TRUE,font=Env$police,variable=taille.axes,resolution=0.1,orient="horizontal")
  taille.legendes=tclVar("1")
  taille.legendes.choose=tkscale(frame5,from=0.5,to=4,showvalue=TRUE,font=Env$police,variable=taille.legendes,resolution=0.1,orient="horizontal")
  xlegendeValue=tclVar("")
  x.legende=tkentry(frame5,width=20,font=Env$police,textvariable=xlegendeValue)
  nom.groupes.but=tkbutton(frame5,text=Env$vocab[111,1],font=Env$police,width=16,command=function() {noms1(type=if (nchar(tclvalue(fact2Value))>0 & tclvalue(fact2Value)!=Env$vocab[48,1]) {"bar2"} else {"bar1"},fact=tclvalue(fact1Value),noms=Env$noms1)})
  ylegendeValue=tclVar("")
  y.legende=tkentry(frame5,width=20,font=Env$police,textvariable=ylegendeValue)
  yinfValue=tclVar("Auto")
  y.inf=tkentry(frame5,width=5,font=Env$police,textvariable=yinfValue)
  ysupValue=tclVar("Auto")
  y.sup=tkentry(frame5,width=5,font=Env$police,textvariable=ysupValue)
  logValue=tclVar(0)
  log.check=tkcheckbutton(frame5,font=Env$police)
  tkconfigure(log.check,variable=logValue)
  tkgrid(tklabel(frame5,text=Env$vocab[86,1],font=Env$police),row=0,column=1,sticky="e")
  tkgrid(col.axes.choose,row=0,column=2,sticky="w")
  tkgrid(tklabel(frame5,text="                                                 ",font=Env$police),row=0,column=3)
  tkgrid(tklabel(frame5,text=Env$vocab[88,1],font=Env$police),row=0,column=4,sticky="se")
  tkgrid(taille.axes.choose,row=0,column=5,sticky="w")
  tkgrid(tklabel(frame5,text=Env$vocab[61,1],font=Env$police),row=1,column=1,sticky="e")
  tkgrid(col.legendes.choose,row=1,column=2,sticky="w")
  tkgrid(tklabel(frame5,text=Env$vocab[63,1],font=Env$police),row=1,column=4,sticky="se")
  tkgrid(taille.legendes.choose,row=1,column=5,sticky="w")
  tkgrid(tklabel(frame5,text="",font=tkfont.create(family="Arial",size=6)))
  tkgrid(tklabel(frame5,text=Env$vocab[64,1],font=tkfont.create(family="Arial",size=10,weight="bold")),row=3,column=1,columnspan=2)
  tkgrid(tklabel(frame5,text=Env$vocab[65,1],font=tkfont.create(family="Arial",size=10,weight="bold")),row=3,column=4,columnspan=2)
  tkgrid(tklabel(frame5,text=" ",font=tkfont.create(family="Arial",size=3)))
  tkgrid(tklabel(frame5,text=Env$vocab[54,1],font=Env$police),row=5,column=1,sticky="e")
  tkgrid(x.legende,row=5,column=2,sticky="w")
  tkgrid(tklabel(frame5,text=Env$vocab[54,1],font=Env$police),row=5,column=4,sticky="e")
  tkgrid(y.legende,row=5,column=5,sticky="w")
  tkgrid(tklabel(frame5,text=Env$vocab[112,1],font=Env$police),row=6,column=1,sticky="e")
  tkgrid(nom.groupes.but,row=6,column=2,sticky="we")
  tkgrid(tklabel(frame5,text=Env$vocab[67,1],font=Env$police),row=6,column=4,sticky="e")
  tkgrid(y.inf,row=6,column=5,sticky="w")
  tkgrid(tklabel(frame5,text=Env$vocab[68,1],font=Env$police),row=7,column=4,sticky="e")
  tkgrid(y.sup,row=7,column=5,sticky="w")
  tkgrid(tklabel(frame5,text=Env$vocab[92,1],font=Env$police),row=8,column=4,sticky="e")
  tkgrid(log.check,row=8,column=5,sticky="w")
  tkpack(frame5)
  frame6=tkframe(frametot)
  tkgrid(tklabel(frame6,text=" ",font=tkfont.create(family="Arial",size=4)))
  tkgrid(tklabel(frame6,image=tkimage.create("photo",file=file.path(.path.package("GrapheR"),"images",Env$images[17,1],fsep=.Platform$file.sep)),width=800,height=21))
  tkpack(frame6)
  frame7=tkframe(frametot)																	# Fenêtre 8 - frame 7 : barres
  col.batons.but=tkbutton(frame7,text=Env$vocab[113,1],font=Env$police,width=20,command=function() {barres.col.barres(varValue=varValue,fact2Value=fact2Value)})
  motif.but=tkbutton(frame7,text=Env$vocab[114,1],font=Env$police,width=20,command=function() {barres.motifs(varValue=varValue,fact2Value=fact2Value)})
  col.bordures.but=tkbutton(frame7,text=Env$vocab[115,1],font=Env$police,width=20,command=function() {barres.col.bordures(varValue=varValue,fact2Value=fact2Value)})
  besideValue=tclVar(0)
  beside.check=tkcheckbutton(frame7,font=Env$police)
  tkconfigure(beside.check,variable=besideValue)
  tkbind(beside.check,"<ButtonRelease-1>",function() {barres.stack(varValue=varValue,fact2Value=fact2Value,besideValue=besideValue,erreur.lab=erreur.lab,erreur.choose=erreur.choose,col.erreur.lab=col.erreur.lab,col.erreur=col.erreur,
    col.erreur.choose=col.erreur.choose,segment.lab=segment.lab,segment.check=segment.check,typeValue=typeValue)})
  tkgrid(col.batons.but,row=0,column=1,sticky="w")
  tkgrid(tklabel(frame7,text="                 ",font=Env$police),row=0,column=2)
  tkgrid(motif.but,row=0,column=3,sticky="w")
  tkgrid(tklabel(frame7,text="                 ",font=Env$police),row=0,column=4)
  tkgrid(col.bordures.but,row=0,column=5,sticky="w")
  tkgrid(tklabel(frame7,text="                 ",font=Env$police),row=0,column=6)
  tkgrid(tklabel(frame7,text=Env$vocab[116,1],font=Env$police),row=0,column=7,sticky="e")
  tkgrid(beside.check,row=0,column=8,sticky="w")
  tkpack(frame7)
  frame8=tkframe(frametot)
  tkgrid(tklabel(frame8,text=" ",font=tkfont.create(family="Arial",size=4)))
  tkgrid(tklabel(frame8,image=tkimage.create("photo",file=file.path(.path.package("GrapheR"),"images",Env$images[22,1],fsep=.Platform$file.sep)),width=800,height=21))
  tkpack(frame8)
  frame9=tkframe(frametot)																	# Fenêtre 8 - frame 9 : barres d'erreur
  erreur.lab=tklabel(frame9,text=Env$vocab[117,1],font=Env$police)
  erreurValue=tclVar()
  erreur.choose=ttkcombobox(frame9,font=Env$police,values=c(Env$vocab[118,1],Env$vocab[119,1],Env$vocab[120,1],Env$vocab[121,1]),textvariable=erreurValue,state="readonly")
  col.erreur.lab=tklabel(frame9,text=Env$vocab[56,1],font=Env$police)
  col.erreur=tclVar("black")
  col.erreur.choose=tkcanvas(frame9,width="25",height="20",bg=tclvalue(col.erreur))
  tkbind(col.erreur.choose,"<ButtonRelease-1>",function() {couleur(fen=Fen8,titre=122,var=col.erreur,widg=col.erreur.choose,type="can",plusieurs=FALSE)})
  segment.lab=tklabel(frame9,text=Env$vocab[123,1],font=Env$police)
  segmentValue=tclVar(0)
  segment.check=tkcheckbutton(frame9,font=Env$police)
  tkconfigure(segment.check,variable=segmentValue)
  tkgrid(erreur.lab,row=0,column=1,sticky="e")
  tkgrid(erreur.choose,row=0,column=2,sticky="w")
  tkgrid(tklabel(frame9,text="                         ",font=Env$police),row=0,column=3)
  tkgrid(col.erreur.lab,row=0,column=4)
  tkgrid(col.erreur.choose,row=0,column=5)
  tkgrid(tklabel(frame9,text="                         ",font=Env$police),row=0,column=6)
  tkgrid(segment.lab,row=0,column=7,sticky="e")
  tkgrid(segment.check,row=0,column=8,sticky="w")
  tkpack(frame9)
  frame10=tkframe(frametot)
  tkgrid(tklabel(frame10,text=" ",font=tkfont.create(family="Arial",size=4)))
  tkgrid(tklabel(frame10,image=tkimage.create("photo",file=file.path(.path.package("GrapheR"),"images",Env$images[23,1],fsep=.Platform$file.sep)),width=800,height=21))
  tkpack(frame10)
  frame11=tkframe(frametot)																	# Fenêtre 8 - frame 11 : légende
  legende.lab=tklabel(frame11,text=Env$vocab[66,1],foreground="grey",font=Env$police)
  legendeValue=tclVar(0)
  legende.check=tkcheckbutton(frame11,font=Env$police,variable=legendeValue)
  tkconfigure(legende.check,variable=legendeValue,state="disabled")
  nom.legende.lab=tklabel(frame11,text=Env$vocab[124,1],foreground="grey",font=Env$police)
  nom.legende.but=tkbutton(frame11,text=Env$vocab[111,1],font=Env$police,width=16,state="disabled",command=function() {legende(type="bar",nb.niv=Env$nb.niv2,noms=Env$noms2,titre=Env$legende.titre)})
  legende.pos.lab=tklabel(frame11,text=Env$vocab[125,1],foreground="grey",font=Env$police)
  legende.posValue=tclVar(Env$vocab[126,1])
  legende.pos.choose=ttkcombobox(frame11,font=Env$police,values=c(Env$vocab[126,1],Env$vocab[127,1],Env$vocab[128,1],Env$vocab[129,1],Env$vocab[130,1],Env$vocab[131,1],Env$vocab[132,1],Env$vocab[133,1],Env$vocab[134,1]),textvariable=legende.posValue,state="readonly")
  tkconfigure(legende.pos.choose,state="disabled")
  tkgrid(legende.lab,row=0,column=1,sticky="e")
  tkgrid(legende.check,row=0,column=2,sticky="w")
  tkgrid(tklabel(frame11,text="                                 ",font=Env$police),row=0,column=3)
  tkgrid(nom.legende.lab,row=0,column=4,sticky="e")
  tkgrid(nom.legende.but,row=0,column=5,sticky="w")
  tkgrid(tklabel(frame11,text="                                 ",font=Env$police),row=0,column=6)
  tkgrid(legende.pos.lab,row=0,column=7,sticky="e")
  tkgrid(legende.pos.choose,row=0,column=8,sticky="w")
  tkpack(frame11)
  frame12=tkframe(frametot)
  tkgrid(tklabel(frame12,text="",font=tkfont.create(family="Arial",size=8)))
  tkpack(frame12)
  frame13=tkframe(frametot)																	# Fenêtre 8 - frame 13 : boutons
  tracer=tkbutton(frame13,text=Env$vocab[79,1],font=Env$police,width=25,command=function() {tracer.barres(var=tclvalue(varValue),fact1=tclvalue(fact1Value),fact2=tclvalue(fact2Value),
    type=tclvalue(typeValue),niv.prop=Env$niv.prop,y.inf=tclvalue(yinfValue),y.sup=tclvalue(ysupValue),beside=as.numeric(tclvalue(besideValue)),x.legende=tclvalue(xlegendeValue),
    y.legende=tclvalue(ylegendeValue),col.ax=tclvalue(col.axes),taille.ax=as.numeric(tclvalue(taille.axes)),log.ax=as.numeric(tclvalue(logValue)),col.legende=tclvalue(col.legendes),
    taille.legende=as.numeric(tclvalue(taille.legendes)),noms1=Env$noms1,col.bar=Env$col.str1,col.bor=Env$col.str2,dens.motif=Env$dens.motif,ang.motif=Env$ang.motif,col.motif=Env$col.motif,titre=tclvalue(titreValue),
    col.titre=tclvalue(col.titre),taille.titre=as.numeric(tclvalue(taille.titre)),leg=as.numeric(tclvalue(legendeValue)),leg.titre=Env$legende.titre,pos.leg=tclvalue(legende.posValue),noms2=Env$noms2,
    err.type=tclvalue(erreurValue),err.seg=as.numeric(tclvalue(segmentValue)),err.col=tclvalue(col.erreur),fen=Fen8)})
  fenetre=tkbutton(frame13,text=Env$vocab[80,1],font=Env$police,width=25,command=function() {new.window()})
  retour=tkbutton(frame13,text=Env$vocab[81,1],font=Env$police,width=25,command=function() {back(fen=Fen8)})
  tkgrid(tracer,row=0,column=1)
  tkgrid(tklabel(frame13,text="                  ",font=Env$police),row=0,column=2)
  tkgrid(fenetre,row=0,column=3)
  tkgrid(tklabel(frame13,text="                  ",font=Env$police),row=0,column=4)
  tkgrid(retour,row=0,column=5)
  tkgrid(tklabel(frame13,text=" ",font=tkfont.create(family="Arial",size=3)))
  tkpack(frame13)
  tkpack(frametot)
}

