camembert <-
function() {
  tkwm.withdraw(Env$Fen4)
  Fen18=tktoplevel()
  tktitle(Fen18)="GrapheR"
  tkwm.resizable(Fen18,FALSE,FALSE)
  tcl("wm","protocol",Fen18,"WM_DELETE_WINDOW",function() {if (Env$toolbar.GrapheR==1) {tkdestroy(Env$Toolbar);assign("toolbar.GrapheR",0,pos=Env)};tkdestroy(Fen18);tkdestroy(Env$Fen4);tkdestroy(Env$Fen1)})
  frametot=tkframe(Fen18)
  frame0=tkframe(frametot)
  tkgrid(tklabel(frame0,image=tkimage.create("photo",file=file.path(.path.package("GrapheR"),"images",Env$images[12,1],fsep=.Platform$file.sep)),width=800,height=40))
  tkpack(frame0)
  frame1=tkframe(frametot)																	# Fenêtre 18 - frame 1 : généralités
  varValue=tclVar()
  var.choose=ttkcombobox(frame1,font=Env$police,values=names(Env$datas.GrapheR),textvariable=varValue,state="readonly")
  tkbind(var.choose,"<<ComboboxSelected>>",function() {camembert.var(varValue=varValue)})
  parts.but=tkbutton(frame1,text=Env$vocab[111,1],font=Env$police,width=16,command=function() {parts(var=tclvalue(varValue),nb.niv=Env$nb.niv0,noms=Env$noms0,prop=Env$niv.prop)})
  tkgrid(tklabel(frame1,text=Env$vocab[135,1],font=Env$police),row=0,column=1,sticky="e")
  tkgrid(var.choose,row=0,column=2)
  tkgrid(tklabel(frame1,text="                                                     ",font=Env$police),row=0,column=3)
  tkgrid(tklabel(frame1,text=Env$vocab[136,1],font=Env$police),row=0,column=4)
  tkgrid(parts.but,row=0,column=5,sticky="w")
  tkpack(frame1)
  frame2=tkframe(frametot)
  tkgrid(tklabel(frame2,text=" ",font=tkfont.create(family="Arial",size=4)))
  tkgrid(tklabel(frame2,image=tkimage.create("photo",file=file.path(.path.package("GrapheR"),"images",Env$images[15,1],fsep=.Platform$file.sep)),width=800,height=21))
  tkpack(frame2)
  frame3=tkframe(frametot)																	# Fenêtre 18 - frame 3 : titre
  titreValue=tclVar("")
  titre=tkentry(frame3,width=30,font=Env$police,textvariable=titreValue)
  col.titre=tclVar("black")
  col.titre.choose=tkbutton(frame3,text="Aa",font=tkfont.create(family="Arial",size=10,weight="bold"),command=function() {couleur(fen=Fen18,titre=55,var=col.titre,widg=col.titre.choose,type="but",plusieurs=FALSE)})
  taille.titre=tclVar("1.5")
  taille.titre.choose=tkscale(frame3,from=0.5,to=4,showvalue=TRUE,font=Env$police,variable=taille.titre,resolution=0.1,orient="horizontal")
  tkgrid(tklabel(frame3,text=Env$vocab[54,1],font=Env$police),row=0,column=1)
  tkgrid(titre,row=0,column=2)
  tkgrid(tklabel(frame3,text="                             ",font=Env$police),row=0,column=3)
  tkgrid(tklabel(frame3,text=Env$vocab[56,1],font=Env$police),row=0,column=4)
  tkgrid(col.titre.choose,row=0,column=5)
  tkgrid(tklabel(frame3,text="                             ",font=Env$police),row=0,column=6)
  tkgrid(tklabel(frame3,text=Env$vocab[57,1],font=Env$police),row=0,column=7)
  tkgrid(taille.titre.choose,row=0,column=8)
  tkpack(frame3)
  frame4=tkframe(frametot)
  tkgrid(tklabel(frame4,text=" ",font=tkfont.create(family="Arial",size=4)))
  tkgrid(tklabel(frame4,image=tkimage.create("photo",file=file.path(.path.package("GrapheR"),"images",Env$images[24,1],fsep=.Platform$file.sep)),width=800,height=21))
  tkpack(frame4)
  frame5=tkframe(frametot)																	# Fenêtre 18 - frame 5 : orientation et nom des parts
  labelsValue=tclVar("1")
  labels.check=tkcheckbutton(frame5,font=Env$police)
  tkconfigure(labels.check,variable=labelsValue)
  labels.but=tkbutton(frame5,text=Env$vocab[111,1],font=Env$police,width=16,command=function() {noms.parts(var=tclvalue(varValue),nb.niv=Env$nb.niv1,noms=Env$noms1)})
  rb1=tkradiobutton(frame5,font=Env$police)
  rb2=tkradiobutton(frame5,font=Env$police)
  sensValue=tclVar("am")
  tkconfigure(rb1,variable=sensValue,value="am",text=Env$vocab[138,1])
  tkconfigure(rb2,variable=sensValue,value="iam",text=Env$vocab[139,1])
  ang.dep=tclVar("0")
  ang.dep.choose=tkscale(frame5,from=0,to=380,showvalue=TRUE,font=Env$police,variable=ang.dep,resolution=5,orient="horizontal",length=125)
  tkgrid(tklabel(frame5,text=Env$vocab[83,1],font=Env$police),row=0,column=1,sticky="e")
  tkgrid(rb1,row=0,column=2,sticky="w")
  tkgrid(tklabel(frame5,text="                  ",font=Env$police),row=0,column=3)
  tkgrid(tklabel(frame5,text=Env$vocab[140,1],font=Env$police),row=0,column=4,sticky="e")
  tkgrid(ang.dep.choose,row=0,column=5,sticky="w")
  tkgrid(rb2,row=1,column=2,sticky="w")
  tkgrid(tklabel(frame5,text="",font=Env$police))
  tkgrid(tklabel(frame5,text=Env$vocab[141,1],font=Env$police),row=3,column=1,sticky="e")
  tkgrid(labels.but,row=3,column=2,sticky="w")
  tkgrid(tklabel(frame5,text=Env$vocab[142,1],font=Env$police),row=4,column=1,sticky="e")
  tkgrid(labels.check,row=4,column=2,sticky="w")
  tkpack(frame5)
  frame6=tkframe(frametot)
  tkgrid(tklabel(frame6,text=" ",font=tkfont.create(family="Arial",size=4)))
  tkgrid(tklabel(frame6,image=tkimage.create("photo",file=file.path(.path.package("GrapheR"),"images",Env$images[25,1],fsep=.Platform$file.sep)),width=800,height=21))
  tkpack(frame6)
  frame7=tkframe(frametot)																	# Fenêtre 18 - frame 7 : parts
  col.parts.but=tkbutton(frame7,text=Env$vocab[143,1],font=Env$police,width=20,command=function() {plusieurscouleurs(nb.niv=Env$nb.niv1,noms=Env$noms1,type="cam",str="str1",col=Env$col.str1)})
  motif.but=tkbutton(frame7,text=Env$vocab[114,1],font=Env$police,width=20,command=function() {plusieursmotifs(nb.niv=Env$nb.niv1,noms=Env$noms1,dens.motif=Env$dens.motif,ang.motif=Env$ang.motif,col.motif=Env$col.motif)})
  col.bordure=tclVar("black")
  col.bordure.choose=tkcanvas(frame7,width="25",height="20",bg=tclvalue(col.bordure))
  tkbind(col.bordure.choose,"<ButtonRelease-1>",function() {couleur(fen=Fen18,titre=145,var=col.bordure,widg=col.bordure.choose,type="can")})
  tkgrid(col.parts.but,row=0,column=1,sticky="w")
  tkgrid(tklabel(frame7,text="                                   ",font=Env$police),row=0,column=2)
  tkgrid(motif.but,row=0,column=3,sticky="w")
  tkgrid(tklabel(frame7,text="                              ",font=Env$police),row=0,column=4)
  tkgrid(tklabel(frame7,text=Env$vocab[144,1],font=Env$police),row=0,column=5,sticky="w")
  tkgrid(col.bordure.choose,row=0,column=6,sticky="w")
  tkpack(frame7)
  frame8=tkframe(frametot)
  tkgrid(tklabel(frame8,text=" ",font=tkfont.create(family="Arial",size=4)))
  tkgrid(tklabel(frame8,image=tkimage.create("photo",file=file.path(.path.package("GrapheR"),"images",Env$images[26,1],fsep=.Platform$file.sep)),width=800,height=21))
  tkpack(frame8)
  frame9=tkframe(frametot)																	# Fenêtre 18 - frame 9 : légende
  legendeValue=tclVar("0")
  legende.check=tkcheckbutton(frame9,font=Env$police,variable=legendeValue)
  tkconfigure(legende.check,variable=legendeValue)
  legende.titreValue=tclVar("")
  legende.titre.box=tkentry(frame9,width=30,font=Env$police,textvariable=legende.titreValue)
  legende.posValue=tclVar(Env$vocab[126,1])
  legende.pos.choose=ttkcombobox(frame9,font=Env$police,values=c(Env$vocab[126,1],Env$vocab[127,1],Env$vocab[128,1],Env$vocab[129,1],Env$vocab[130,1],Env$vocab[131,1],Env$vocab[132,1],Env$vocab[133,1],Env$vocab[134,1]),textvariable=legende.posValue,state="readonly")
  tkgrid(tklabel(frame9,text=Env$vocab[66,1],font=Env$police),row=0,column=1,sticky="e")
  tkgrid(legende.check,row=0,column=2,sticky="w")
  tkgrid(tklabel(frame9,text="                         ",font=Env$police),row=0,column=3)
  tkgrid(tklabel(frame9,text=Env$vocab[54,1],font=Env$police),row=0,column=4,sticky="e")
  tkgrid(legende.titre.box,row=0,column=5,sticky="w")
  tkgrid(tklabel(frame9,text="                         ",font=Env$police),row=0,column=6)
  tkgrid(tklabel(frame9,text=Env$vocab[125,1],font=Env$police),row=0,column=7,sticky="e")
  tkgrid(legende.pos.choose,row=0,column=8,sticky="w")
  tkpack(frame9)
  frame10=tkframe(frametot)
  tkgrid(tklabel(frame10,text="",font=tkfont.create(family="Arial",size=8)))
  tkpack(frame10)
  frame11=tkframe(frametot)																	# Fenêtre 18 - frame 11 : boutons
  tracer=tkbutton(frame11,text=Env$vocab[79,1],font=Env$police,width=25,command=function() {tracer.camembert(var=tclvalue(varValue),nb.niv=Env$nb.niv1,prop=Env$niv.prop,noms=Env$noms1,
    sens=tclvalue(sensValue),debut=as.numeric(tclvalue(ang.dep)),autour=as.numeric(tclvalue(labelsValue)),col.par=Env$col.str1,col.bor=tclvalue(col.bordure),dens.motif=Env$dens.motif,ang.motif=Env$ang.motif,
    col.motif=Env$col.motif,titre=tclvalue(titreValue),col.titre=tclvalue(col.titre),taille.titre=as.numeric(tclvalue(taille.titre)),leg=as.numeric(tclvalue(legendeValue)),pos.leg=tclvalue(legende.posValue),
    leg.titre=tclvalue(legende.titreValue),fen=Fen18)})
  fenetre=tkbutton(frame11,text=Env$vocab[80,1],font=Env$police,width=25,command=function() {new.window()})
  retour=tkbutton(frame11,text=Env$vocab[81,1],font=Env$police,width=25,command=function() {back(fen=Fen18)})
  tkgrid(tracer,row=0,column=1)
  tkgrid(tklabel(frame11,text="                  ",font=Env$police),row=0,column=2)
  tkgrid(fenetre,row=0,column=3)
  tkgrid(tklabel(frame11,text="                  ",font=Env$police),row=0,column=4)
  tkgrid(retour,row=0,column=5)
  tkgrid(tklabel(frame11,text="",font=tkfont.create(family="Arial",size=3)))
  tkpack(frame11)
  tkpack(frametot)
}

