commencer <-
function() {
  assign("Fen1",tktoplevel(),pos=Env)														# Fenêtre 1 : chargement des données
  tktitle(Env$Fen1)="GrapheR"
  tkwm.resizable(Env$Fen1,FALSE,FALSE)
  frameTot=tkframe(Env$Fen1)
  frame0=tkframe(frameTot)
  tkgrid(tklabel(frame0,text=" ",font=tkfont.create(family="Arial",size=1)))
  tkgrid(tklabel(frame0,image=tkimage.create("photo",file=file.path(.path.package("GrapheR"),"images",Env$images[7,1],fsep=.Platform$file.sep)),width=800,height=21))
  tkgrid(tklabel(frame0,text=" ",font=tkfont.create(family="Arial",size=4)))
  tkpack(frame0)
  frame1=tkframe(frameTot)																	# Fenêtre 1 - frame 1 : chargement du fichier
  ext.value=tclVar("Txt")
  ext.choose=ttkcombobox(frame1,values=c("Txt","Csv"),textvariable=ext.value,font=Env$police,state="readonly")
  NA.value=tclVar("NA")
  NA.cod=tkentry(frame1,width=4,textvariable=NA.value,font=Env$police)
  header.value=tclVar(1)
  header.check=tkcheckbutton(frame1,variable=header.value,font=Env$police)
  sep.value=tclVar(Env$vocab[10,1])
  sep.choose=ttkcombobox(frame1,values=c(Env$vocab[10,1],Env$vocab[12,1],Env$vocab[13,1]),textvariable=sep.value,font=Env$police,state="readonly")
  dec.value=tclVar(Env$vocab[11,1])
  dec.choose=ttkcombobox(frame1,values=c(Env$vocab[11,1],Env$vocab[12,1]),textvariable=dec.value,font=Env$police,state="readonly")
  charger.but=tkbutton(frame1,text=Env$vocab[32,1],width=37,font=Env$police,command=function() {charger(ext=tclvalue(ext.value),dcm=tclvalue(dec.value),hdr=as.integer(tclvalue(header.value)),
    na.cod=tclvalue(NA.value),spr=tclvalue(sep.value),rsm=resume)})
  tkgrid(tklabel(frame1,text=Env$vocab[14,1],font=Env$police),row=1,column=1,sticky="e")
  tkgrid(ext.choose,row=1,column=2,sticky="w")
  tkgrid(tklabel(frame1,text="                                           ",font=Env$police),row=1,column=3)
  tkgrid(tklabel(frame1,text=Env$vocab[15,1],font=Env$police),row=1,column=4,sticky="e")
  tkgrid(NA.cod,row=1,column=5,sticky="w")
  tkgrid(tklabel(frame1,text=Env$vocab[16,1],font=Env$police),row=2,column=1,sticky="e")
  tkgrid(sep.choose,row=2,column=2,sticky="w")
  tkgrid(tklabel(frame1,text=Env$vocab[17,1],font=Env$police),row=2,column=4,sticky="e")
  tkgrid(header.check,row=2,column=5,sticky="w")
  tkgrid(tklabel(frame1,text=Env$vocab[18,1],font=Env$police),row=3,column=1,sticky="e")
  tkgrid(dec.choose,row=3,column=2,sticky="w")
  tkgrid(tklabel(frame1,text="",font=Env$police))
  tkgrid(charger.but,columnspan=10)
  tkpack(frame1)
  frame2=tkframe(frameTot)
  tkgrid(tklabel(frame2,text=" ",font=tkfont.create(family="Arial",size=7)))
  tkgrid(tklabel(frame2,image=tkimage.create("photo",file=file.path(.path.package("GrapheR"),"images",Env$images[8,1],fsep=.Platform$file.sep)),width=800,height=21))
  tkgrid(tklabel(frame2,text=" ",font=tkfont.create(family="Arial",size=4)))
  tkpack(frame2)
  frame3=tkframe(frameTot)																	# Fenêtre 1 - frame 3 : infos sur le jeu de données
  resume=tktext(frame3,height=2,font=Env$police)
  tkconfigure(resume,state="disabled")
  assign("var.num.list",tklistbox(frame3,height=7,font=Env$police,selectmode="single",yscrollcommand=function(...) tkset(var.num.scroll,...)),pos=Env)
  var.num.scroll=tkscrollbar(frame3,repeatinterval=5,command=function(...) tkyview(Env$var.num.list,...))
  assign("fact.list",tklistbox(frame3,height=7,font=Env$police,selectmode="single",yscrollcommand=function(...) tkset(fact.scroll,...)),pos=Env)
  fact.scroll=tkscrollbar(frame3,repeatinterval=5,command=function(...) tkyview(Env$fact.list,...))
  renommer=tkbutton(frame3,text=Env$vocab[33,1],width=37,font=Env$police,command=function() {renommer()})
  transformer=tkbutton(frame3,text=Env$vocab[34,1],width=37,font=Env$police,command=function() {transformer()})
  assign("info",tktext(frame3,height=1,font=Env$police),pos=Env)
  tkconfigure(Env$info,state="disabled")
  tkbind(Env$var.num.list,"<ButtonRelease-1>",function() {
    tkconfigure(Env$Fen1,cursor="watch")
    numero=as.numeric(tclvalue(tkcurselection(Env$var.num.list)))+1
    tkconfigure(Env$info,state="normal")
    tkdelete(Env$info,"0.0","end")
    tkinsert(Env$info,"end",paste(Env$vocab[26,1],names(Env$datas.GrapheR)[Env$variables=="N"][numero],Env$vocab[28,1],length(Env$datas.GrapheR[,which(Env$variables=="N")[numero]]),Env$vocab[30,1],length(which(is.na(Env$datas.GrapheR[,which(Env$variables=="N")][numero])==TRUE)),Env$vocab[31,1]))
    tkconfigure(Env$info,state="disabled")
    tkconfigure(Env$Fen1,cursor="arrow")
  })
  tkbind(Env$fact.list,"<ButtonRelease-1>",function() {
    tkconfigure(Env$Fen1,cursor="watch")
    numero=as.numeric(tclvalue(tkcurselection(Env$fact.list)))+1
    tkconfigure(Env$info,state="normal")
    tkdelete(Env$info,"0.0","end")
    tkinsert(Env$info,"end",paste(Env$vocab[27,1],names(Env$datas.GrapheR)[Env$variables=="F"][numero],Env$vocab[28,1],nlevels(Env$datas.GrapheR[,which(Env$variables=="F")[numero]]),Env$vocab[29,1],length(Env$datas.GrapheR[,which(Env$variables=="F")[numero]]),Env$vocab[30,1],length(which(is.na(Env$datas.GrapheR[,which(Env$variables=="F")][numero])==TRUE)),Env$vocab[31,1]))
    tkconfigure(Env$info,state="disabled")
    tkconfigure(Env$Fen1,cursor="arrow")
  })
  graphe=tkbutton(frame3,text=Env$vocab[35,1],width=37,font=Env$police,command=function() {graphe.choix()})
  tkgrid(resume,column=1,columnspan=5,sticky="we")
  tkgrid(tklabel(frame3,text="",font=Env$police))
  tkgrid(tklabel(frame3,text=Env$vocab[24,1],font=Env$police),row=5,column=1)
  tkgrid(tklabel(frame3,text="                        ",font=Env$police),row=5,column=2)
  tkgrid(tklabel(frame3,text="                        ",font=Env$police),row=5,column=4)
  tkgrid(tklabel(frame3,text=Env$vocab[25,1],font=Env$police),row=5,column=5)
  tkgrid(Env$var.num.list,var.num.scroll,row=6,column=1,rowspan=2);tkgrid.configure(var.num.scroll,sticky="ens")
  tkgrid(renommer,row=6,column=3,sticky="we")
  tkgrid(transformer,row=7,column=3,sticky="we")
  tkgrid(Env$fact.list,fact.scroll,row=6,column=5,rowspan=2);tkgrid.configure(fact.scroll,sticky="ens")
  tkgrid(tklabel(frame3,text="",font=Env$police))
  tkgrid(Env$info,column=1,columnspan=5,sticky="we")
  tkgrid(tklabel(frame3,text="",font=Env$police))
  tkgrid(graphe,column=3,sticky="we")
  tkgrid(tklabel(frame3,text=" ",font=tkfont.create(family="Arial",size=4)))
  tkpack(frame3)
  tkpack(frameTot)
}

