courbe <-
function() {
  tkwm.withdraw(Env$Fen4)
  Fen29=tktoplevel()
  tktitle(Fen29)="GrapheR"
  tkwm.resizable(Fen29,FALSE,FALSE)
  tcl("wm","protocol",Fen29,"WM_DELETE_WINDOW",function() {if (Env$toolbar.GrapheR==1) {tkdestroy(Env$Toolbar);assign("toolbar.GrapheR",0,pos=Env)};tkdestroy(Fen29);tkdestroy(Env$Fen4);tkdestroy(Env$Fen1)})
  frametot=tkframe(Fen29)
  frame0=tkframe(frametot)
  tkgrid(tklabel(frame0,image=tkimage.create("photo",file=file.path(.path.package("GrapheR"),"images",Env$images[13,1],fsep=.Platform$file.sep)),width=800,height=40))
  tkpack(frame0)
  frame1=tkframe(frametot)																	# Fenêtre 29 - frame 1 : généralités
  var1Value=tclVar()
  var1.choose=ttkcombobox(frame1,font=Env$police,values=names(Env$datas.GrapheR[which(Env$variables=="N")]),textvariable=var1Value,state="readonly",width=15)
  var2Value=tclVar()
  var2.choose=ttkcombobox(frame1,font=Env$police,values=names(Env$datas.GrapheR),textvariable=var2Value,state="readonly",width=15)
  tkbind(var2.choose,"<<ComboboxSelected>>",function() {courbe.vary(var2Value=var2Value,erreur.lab=erreur.lab,erreur.choose=erreur.choose,segment.lab=segment.lab,segment.check=segment.check,niv.lab=niv.lab,niv.choose=niv.choose,
    nivValue=nivValue,typeValue=typeValue,rb1=rb1,rb2=rb2,rb3=rb3)})
  niv.lab=tklabel(frame1,text=Env$vocab[148,1],foreground="grey",font=Env$police)
  nivValue=tclVar()
  niv.choose=ttkcombobox(frame1,font=Env$police,values="",textvariable=nivValue,state="disabled",width=15)
  factValue=tclVar()
  assign("niv.fact","",pos=Env)
  assign("symb",1,pos=Env)
  assign("col.str1","black",pos=Env)
  assign("lignes",Env$vocab[166,1],pos=Env)
  assign("traits",Env$vocab[75,1],pos=Env)
  assign("ep.lignes",1,pos=Env)
  assign("legende.titre","",pos=Env)
  fact.choose=ttkcombobox(frame1,font=Env$police,values=c(Env$vocab[48,1],names(Env$datas.GrapheR[which(Env$variables=="F")])),textvariable=factValue,state="readonly",width=15)
  tkbind(fact.choose,"<<ComboboxSelected>>",function() {courbe.fact(factValue=factValue,niv.but=niv.but,legende.lab=legende.lab,legende.check=legende.check,nom.legende.lab=nom.legende.lab,nom.legende.but=nom.legende.but,
    legende.pos.lab=legende.pos.lab,legende.pos.choose=legende.pos.choose)})
  niv.but=tkbutton(frame1,text=Env$vocab[111,1],font=Env$police,width=15,state="disabled",command=function() {niv(fact=tclvalue(factValue),niv=Env$niv.fact)})
  rb1=tkradiobutton(frame1,font=Env$police,command=function() {courbe.type1(erreur.choose=erreur.choose,erreur.lab=erreur.lab,segment.lab=segment.lab,segment.check=segment.check)})
  rb2=tkradiobutton(frame1,font=Env$police,command=function() {courbe.type2(erreur.choose=erreur.choose,erreur.lab=erreur.lab,segment.lab=segment.lab,segment.check=segment.check)})
  rb3=tkradiobutton(frame1,font=Env$police)
  typeValue=tclVar("moy")
  tkconfigure(rb1,variable=typeValue,value="som",text=Env$vocab[108,1])
  tkconfigure(rb2,variable=typeValue,value="moy",text=Env$vocab[109,1])
  tkconfigure(rb3,variable=typeValue,value="prop",text=Env$vocab[110,1])
  boxValue=tclVar("0")
  box.check=tkcheckbutton(frame1,font=Env$police)
  tkconfigure(box.check,variable=boxValue)
  tkgrid(tklabel(frame1,text=Env$vocab[146,1],font=Env$police),row=0,column=1,sticky="e")
  tkgrid(var1.choose,row=0,column=2,sticky="w")
  tkgrid(tklabel(frame1,text="             ",font=Env$police),row=0,column=3)
  tkgrid(tklabel(frame1,text=Env$vocab[149,1],font=Env$police),row=0,column=4,rowspan=2,sticky="e")
  tkgrid(fact.choose,row=0,column=5,rowspan=2,sticky="w")
  tkgrid(tklabel(frame1,text="             ",font=Env$police),row=0,column=6)
  tkgrid(rb1,row=0,column=8,sticky="w")
  tkgrid(tklabel(frame1,text="             ",font=Env$police),row=0,column=10)
  tkgrid(tklabel(frame1,text=Env$vocab[147,1],font=Env$police),row=1,column=1,sticky="e")
  tkgrid(var2.choose,row=1,column=2,sticky="w")
  tkgrid(tklabel(frame1,text=Env$vocab[107,1],font=Env$police),row=1,column=7,sticky="e")
  tkgrid(rb2,row=1,column=8,sticky="w")
  tkgrid(niv.lab,row=2,column=1,sticky="e")
  tkgrid(niv.choose,row=2,column=2,sticky="w")
  tkgrid(tklabel(frame1,text=Env$vocab[150,1],font=Env$police),row=2,column=4,sticky="e")
  tkgrid(niv.but,row=2,column=5,sticky="w")
  tkgrid(rb3,row=2,column=8,sticky="w")
  tkgrid(tklabel(frame1,text=Env$vocab[151,1],font=Env$police),row=1,column=11,sticky="e")
  tkgrid(box.check,row=1,column=12,sticky="w")
  tkpack(frame1)
  frame2=tkframe(frametot)
  tkgrid(tklabel(frame2,text=" ",font=tkfont.create(family="Arial",size=4)))
  tkgrid(tklabel(frame2,image=tkimage.create("photo",file=file.path(.path.package("GrapheR"),"images",Env$images[15,1],fsep=.Platform$file.sep)),width=800,height=21))
  tkpack(frame2)
  frame3=tkframe(frametot)																	# Fenêtre 29 - frame 3 : titre
  titreValue=tclVar("")
  titre=tkentry(frame3,width=30,font=Env$police,textvariable=titreValue)
  col.titre=tclVar("black")
  col.titre.choose=tkbutton(frame3,text="Aa",font=tkfont.create(family="Arial",size=10,weight="bold"),command=function() {couleur(fen=Fen29,titre=55,var=col.titre,widg=col.titre.choose,type="but",plusieurs=FALSE)})
  taille.titre=tclVar("1.5")
  taille.titre.choose=tkscale(frame3,from=0.5,to=4,showvalue=TRUE,font=Env$police,variable=taille.titre,resolution=0.1,orient="horizontal")
  tkgrid(tklabel(frame3,text=Env$vocab[54,1],font=Env$police),row=0,column=1)
  tkgrid(titre,row=0,column=2)
  tkgrid(tklabel(frame3,text="                             ",font=Env$police),row=0,column=3)
  tkgrid(tklabel(frame3,text=Env$vocab[56,1],font=Env$police),row=0,column=4)
  tkgrid(col.titre.choose,row=0,column=5)
  tkgrid(tklabel(frame3,text="                             ",font=Env$police),row=0,column=6)
  tkgrid(tklabel(frame3,text=Env$vocab[57,1],font=Env$police),row=0,column=7)
  tkgrid(taille.titre.choose,row=0,column=8)
  tkpack(frame3)
  frame4=tkframe(frametot)
  tkgrid(tklabel(frame4,text=" ",font=tkfont.create(family="Arial",size=4)))
  tkgrid(tklabel(frame4,image=tkimage.create("photo",file=file.path(.path.package("GrapheR"),"images",Env$images[16,1],fsep=.Platform$file.sep)),width=800,height=21))
  tkpack(frame4)
  frame5=tkframe(frametot)																	# Fenêtre 29 - frame 5 : axes
  col.axes=tclVar("black")
  col.axes.choose=tkbutton(frame5,text="Aa",font=tkfont.create(family="Arial",size=10,weight="bold"),command=function() {couleur(fen=Fen29,titre=59,var=col.axes,widg=col.axes.choose,type="but",plusieurs=FALSE)})
  col.legendes=tclVar("black")
  col.legendes.choose=tkbutton(frame5,text="Aa",font=tkfont.create(family="Arial",size=10,weight="bold"),command=function() {couleur(fen=Fen29,titre=62,var=col.legendes,widg=col.legendes.choose,type="but",plusieurs=FALSE)})
  taille.axes=tclVar("1")
  taille.axes.choose=tkscale(frame5,from=0.5,to=4,showvalue=TRUE,font=Env$police,variable=taille.axes,resolution=0.1,orient="horizontal")
  taille.legendes=tclVar("1")
  taille.legendes.choose=tkscale(frame5,from=0.5,to=4,showvalue=TRUE,font=Env$police,variable=taille.legendes,resolution=0.1,orient="horizontal")
  xlegendeValue=tclVar("")
  x.legende=tkentry(frame5,width=20,font=Env$police,textvariable=xlegendeValue)
  xinfValue=tclVar("Auto")
  x.inf=tkentry(frame5,width=5,font=Env$police,textvariable=xinfValue)
  xsupValue=tclVar("Auto")
  x.sup=tkentry(frame5,width=5,font=Env$police,textvariable=xsupValue)
  xlogValue=tclVar("0")
  xlog.check=tkcheckbutton(frame5,font=Env$police)
  tkconfigure(xlog.check,variable=xlogValue)
  ylegendeValue=tclVar("")
  y.legende=tkentry(frame5,width=20,font=Env$police,textvariable=ylegendeValue)
  yinfValue=tclVar("Auto")
  y.inf=tkentry(frame5,width=5,font=Env$police,textvariable=yinfValue)
  ysupValue=tclVar("Auto")
  y.sup=tkentry(frame5,width=5,font=Env$police,textvariable=ysupValue)
  ylogValue=tclVar("0")
  ylog.check=tkcheckbutton(frame5,font=Env$police)
  tkconfigure(ylog.check,variable=ylogValue)
  tkgrid(tklabel(frame5,text=Env$vocab[58,1],font=Env$police),row=0,column=1,sticky="e")
  tkgrid(col.axes.choose,row=0,column=2,sticky="w")
  tkgrid(tklabel(frame5,text="                                              ",font=Env$police),row=0,column=3)
  tkgrid(tklabel(frame5,text=Env$vocab[60,1],font=Env$police),row=0,column=4,sticky="se")
  tkgrid(taille.axes.choose,row=0,column=5,sticky="w")
  tkgrid(tklabel(frame5,text=Env$vocab[61,1],font=Env$police),row=1,column=1,sticky="e")
  tkgrid(col.legendes.choose,row=1,column=2,sticky="w")
  tkgrid(tklabel(frame5,text=Env$vocab[63,1],font=Env$police),row=1,column=4,sticky="se")
  tkgrid(taille.legendes.choose,row=1,column=5,sticky="w")
  tkgrid(tklabel(frame5,text="",font=tkfont.create(family="Arial",size=6)))
  tkgrid(tklabel(frame5,text=Env$vocab[64,1],font=tkfont.create(family="Arial",size=10,weight="bold")),row=3,column=1,columnspan=2)
  tkgrid(tklabel(frame5,text=Env$vocab[65,1],font=tkfont.create(family="Arial",size=10,weight="bold")),row=3,column=4,columnspan=2)
  tkgrid(tklabel(frame5,text="",font=tkfont.create(family="Arial",size=3)))
  tkgrid(tklabel(frame5,text=Env$vocab[54,1],font=Env$police),row=5,column=1,sticky="e")
  tkgrid(x.legende,row=5,column=2,sticky="w")
  tkgrid(tklabel(frame5,text=Env$vocab[54,1],font=Env$police),row=5,column=4,sticky="e")
  tkgrid(y.legende,row=5,column=5,sticky="w")
  tkgrid(tklabel(frame5,text=Env$vocab[67,1],font=Env$police),row=6,column=1,sticky="e")
  tkgrid(x.inf,row=6,column=2,sticky="w")
  tkgrid(tklabel(frame5,text=Env$vocab[67,1],font=Env$police),row=6,column=4,sticky="e")
  tkgrid(y.inf,row=6,column=5,sticky="w")
  tkgrid(tklabel(frame5,text=Env$vocab[68,1],font=Env$police),row=7,column=1,sticky="e")
  tkgrid(x.sup,row=7,column=2,sticky="w")
  tkgrid(tklabel(frame5,text=Env$vocab[68,1],font=Env$police),row=7,column=4,sticky="e")
  tkgrid(y.sup,row=7,column=5,sticky="w")
  tkgrid(tklabel(frame5,text=Env$vocab[92,1],font=Env$police),row=8,column=1,sticky="e")
  tkgrid(xlog.check,row=8,column=2,sticky="w")
  tkgrid(tklabel(frame5,text=Env$vocab[92,1],font=Env$police),row=8,column=4,sticky="e")
  tkgrid(ylog.check,row=8,column=5,sticky="w")
  tkpack(frame5)
  frame6=tkframe(frametot)
  tkgrid(tklabel(frame6,text=" ",font=tkfont.create(family="Arial",size=4)))
  tkgrid(tklabel(frame6,image=tkimage.create("photo",file=file.path(.path.package("GrapheR"),"images",Env$images[27,1],fsep=.Platform$file.sep)),width=800,height=21))
  tkpack(frame6)
  frame7=tkframe(frametot)																	# Fenêtre 29 - frame 7 : points et courbes
  symb.but=tkbutton(frame7,text=Env$vocab[152,1],font=Env$police,width=25,command=function() {courbe.symbol(factValue=factValue)})
  taille.pt=tclVar("1")
  taille.pt.choose=tkscale(frame7,from=0.3,to=3,showvalue=TRUE,font=Env$police,variable=taille.pt,resolution=0.1,orient="horizontal")
  courbe.but=tkbutton(frame7,text=Env$vocab[154,1],font=Env$police,width=25,command=function() {courbe.droite(factValue=factValue)})
  tkgrid(symb.but,row=0,column=1)
  tkgrid(tklabel(frame7,text="                        ",font=Env$police),row=0,column=2)
  tkgrid(tklabel(frame7,text=Env$vocab[153,1],font=Env$police),row=0,column=3,sticky="e")
  tkgrid(taille.pt.choose,row=0,column=4,sticky="w")
  tkgrid(tklabel(frame7,text="                        ",font=Env$police),row=0,column=5)
  tkgrid(courbe.but,row=0,column=6)
  tkpack(frame7)
  frame8=tkframe(frametot)
  tkgrid(tklabel(frame8,text=" ",font=tkfont.create(family="Arial",size=4)))
  tkgrid(tklabel(frame8,image=tkimage.create("photo",file=file.path(.path.package("GrapheR"),"images",Env$images[22,1],fsep=.Platform$file.sep)),width=800,height=21))
  tkpack(frame8)
  frame9=tkframe(frametot)																	# Fenêtre 29 - frame 9 : barres d'erreur
  erreur.lab=tklabel(frame9,text=Env$vocab[117,1],font=Env$police)
  erreurValue=tclVar()
  erreur.choose=ttkcombobox(frame9,font=Env$police,values=c(Env$vocab[118,1],Env$vocab[119,1],Env$vocab[120,1],Env$vocab[120,1]),textvariable=erreurValue,state="readonly")
  segment.lab=tklabel(frame9,text=Env$vocab[123,1],font=Env$police)
  segmentValue=tclVar("0")
  segment.check=tkcheckbutton(frame9,font=Env$police)
  tkconfigure(segment.check,variable=segmentValue)
  tkgrid(erreur.lab,row=0,column=1,sticky="e")
  tkgrid(erreur.choose,row=0,column=2,sticky="w")
  tkgrid(tklabel(frame9,text="                                                       ",font=Env$police),row=0,column=3)
  tkgrid(segment.lab,row=0,column=4,sticky="e")
  tkgrid(segment.check,row=0,column=5,sticky="w")
  tkpack(frame9)
  frame10=tkframe(frametot)
  tkgrid(tklabel(frame10,text=" ",font=tkfont.create(family="Arial",size=4)))
  tkgrid(tklabel(frame10,image=tkimage.create("photo",file=file.path(.path.package("GrapheR"),"images",Env$images[23,1],fsep=.Platform$file.sep)),width=800,height=21))
  tkpack(frame10)
  frame11=tkframe(frametot)																	# Fenêtre 29 - frame 11 : légende
  legende.lab=tklabel(frame11,text=Env$vocab[66,1],foreground="grey",font=Env$police)
  legendeValue=tclVar("0")
  legende.check=tkcheckbutton(frame11,font=Env$police,variable=legendeValue)
  tkconfigure(legende.check,variable=legendeValue,state="disabled")
  nom.legende.lab=tklabel(frame11,text=Env$vocab[124,1],foreground="grey",font=Env$police)
  nom.legende.but=tkbutton(frame11,text=Env$vocab[111,1],font=Env$police,width=16,state="disabled",command=function() {legende(type="courbe",nb.niv=Env$nb.niv1,noms=Env$noms1,titre=Env$legende.titre)})
  legende.pos.lab=tklabel(frame11,text=Env$vocab[125,1],foreground="grey",font=Env$police)
  legende.posValue=tclVar(Env$vocab[126,1])
  legende.pos.choose=ttkcombobox(frame11,font=Env$police,values=c(Env$vocab[126,1],Env$vocab[127,1],Env$vocab[128,1],Env$vocab[129,1],Env$vocab[130,1],Env$vocab[131,1],Env$vocab[132,1],Env$vocab[133,1],Env$vocab[134,1]),textvariable=legende.posValue,state="readonly")
  tkconfigure(legende.pos.choose,state="disabled")
  tkgrid(legende.lab,row=0,column=1,sticky="e")
  tkgrid(legende.check,row=0,column=2,sticky="w")
  tkgrid(tklabel(frame11,text="                                  ",font=Env$police),row=0,column=3)
  tkgrid(nom.legende.lab,row=0,column=4,sticky="e")
  tkgrid(nom.legende.but,row=0,column=5,sticky="w")
  tkgrid(tklabel(frame11,text="                                ",font=Env$police),row=0,column=6)
  tkgrid(legende.pos.lab,row=0,column=7,sticky="e")
  tkgrid(legende.pos.choose,row=0,column=8,sticky="w")
  tkpack(frame11)
  frame12=tkframe(frametot)
  tkgrid(tklabel(frame12,text="",font=tkfont.create(family="Arial",size=8)))
  tkpack(frame12)
  frame13=tkframe(frametot)																	# Fenêtre 29 - frame 13 : boutons
  tracer=tkbutton(frame13,text=Env$vocab[79,1],font=Env$police,width=25,command=function() {tracer.courbe(var1=tclvalue(var1Value),var2=tclvalue(var2Value),
    niv1=tclvalue(nivValue),fact=tclvalue(factValue),nb.niv=Env$nb.niv1,niv2=Env$niv.fact,type=tclvalue(typeValue),encadre=as.numeric(tclvalue(boxValue)),
    titre=tclvalue(titreValue),col.titre=tclvalue(col.titre),taille.titre=as.numeric(tclvalue(taille.titre)),col.ax=tclvalue(col.axes),taille.ax=as.numeric(tclvalue(taille.axes)),
    x.legende=tclvalue(xlegendeValue),y.legende=tclvalue(ylegendeValue),taille.legende=as.numeric(tclvalue(taille.legendes)),col.legende=tclvalue(col.legendes),x.inf=tclvalue(xinfValue),
    x.sup=tclvalue(xsupValue),y.inf=tclvalue(yinfValue),y.sup=tclvalue(ysupValue),x.log=as.numeric(tclvalue(xlogValue)),y.log=as.numeric(tclvalue(ylogValue)),symbol=Env$symb,
    taille.symb=as.numeric(tclvalue(taille.pt)),col.symb=Env$col.str1,lig=Env$lignes,tra=Env$traits,ep.lig=Env$ep.lignes,err.type=tclvalue(erreurValue),err.seg=as.numeric(tclvalue(segmentValue)),
    leg=as.numeric(tclvalue(legendeValue)),pos.leg=tclvalue(legende.posValue),leg.titre=Env$legende.titre,noms=Env$noms1,fen=Fen29)})
  fenetre=tkbutton(frame13,text=Env$vocab[80,1],font=Env$police,width=25,command=function() {new.window()})
  retour=tkbutton(frame13,text=Env$vocab[81,1],font=Env$police,width=25,command=function() {back(fen=Fen29)})
  tkgrid(tracer,row=0,column=1)
  tkgrid(tklabel(frame13,text="                  ",font=Env$police),row=0,column=2)
  tkgrid(fenetre,row=0,column=3)
  tkgrid(tklabel(frame13,text="                  ",font=Env$police),row=0,column=4)
  tkgrid(retour,row=0,column=5)
  tkgrid(tklabel(frame13,text="",font=tkfont.create(family="Arial",size=3)))
  tkpack(frame13)
  tkpack(frametot)
}

