histogram <-
function() {
  tkwm.withdraw(Env$Fen4)
  Fen5=tktoplevel()
  tktitle(Fen5)="GrapheR"
  tkwm.resizable(Fen5,FALSE,FALSE)
  tcl("wm","protocol",Fen5,"WM_DELETE_WINDOW",function() {if (Env$toolbar.GrapheR==1) {tkdestroy(Env$Toolbar);assign("toolbar.GrapheR",0,pos=Env)};tkdestroy(Fen5);tkdestroy(Env$Fen4);tkdestroy(Env$Fen1)})
  frametot=tkframe(Fen5)
  frame0=tkframe(frametot)
  tkgrid(tklabel(frame0,image=tkimage.create("photo",file=file.path(.path.package("GrapheR"),"images",Env$images[9,1],fsep=.Platform$file.sep)),width=800,height=40))
  tkpack(frame0)
  frame1=tkframe(frametot)																	# Fenêtre 5 - frame 1 : généralités
  varValue=tclVar()
  var.choose=ttkcombobox(frame1,font=Env$police,values=names(Env$datas.GrapheR[which(Env$variables=="N")]),textvariable=varValue,state="readonly")
  factValue=tclVar()
  fact.choose=ttkcombobox(frame1,font=Env$police,values=c(Env$vocab[48,1],names(Env$datas.GrapheR[which(Env$variables=="F")])),textvariable=factValue,state="readonly")
  tkbind(fact.choose,"<<ComboboxSelected>>",function() {histogram.fact(factValue=factValue,nivValue=nivValue,niv.lab=niv.lab,niv.choose=niv.choose)})
  niv.lab=tklabel(frame1,text=Env$vocab[49,1],font=Env$police,foreground="grey")
  nivValue=tclVar("")
  niv.choose=ttkcombobox(frame1,font=Env$police,values=c(""),textvariable=nivValue,state="disabled")	
  rb1=tkradiobutton(frame1,font=Env$police,command=function() {histogram.type1(x.inf=x.inf,x.sup=x.sup,distrib.lab=distrib.lab,distrib.check=distrib.check,col.distrib.lab=col.distrib.lab,col.distrib=col.distrib,col.distrib.choose=col.distrib.choose,
    type.distrib.lab=type.distrib.lab,type.distrib.choose=type.distrib.choose,ep.distrib.lab=ep.distrib.lab,ep.distrib.choose=ep.distrib.choose)})
  rb2=tkradiobutton(frame1,font=Env$police,command=function() {histogram.type2(x.inf=x.inf,x.sup=x.sup,distrib.lab=distrib.lab,distrib.check=distrib.check,col.distrib.lab=col.distrib.lab,col.distrib=col.distrib,col.distrib.choose=col.distrib.choose,
    type.distrib.lab=type.distrib.lab,type.distrib.choose=type.distrib.choose,ep.distrib.lab=ep.distrib.lab,ep.distrib.choose=ep.distrib.choose)})
  rb3=tkradiobutton(frame1,font=Env$police,command=function() {histogram.type3(x.inf=x.inf,x.sup=x.sup,distrib.lab=distrib.lab,distrib.check=distrib.check,col.distrib.lab=col.distrib.lab,col.distrib=col.distrib,col.distrib.choose=col.distrib.choose,
    type.distrib.lab=type.distrib.lab,type.distrib.choose=type.distrib.choose,ep.distrib.lab=ep.distrib.lab,ep.distrib.choose=ep.distrib.choose)})
  typeValue=tclVar("eff")
  tkconfigure(rb1,variable=typeValue,value="eff",text=Env$vocab[51,1])
  tkconfigure(rb2,variable=typeValue,value="freq",text=Env$vocab[52,1])
  tkconfigure(rb3,variable=typeValue,value="dens",text=Env$vocab[53,1])
  tkgrid(tklabel(frame1,text=Env$vocab[46,1],font=Env$police),row=0,column=1,sticky="e")
  tkgrid(var.choose,row=0,column=2)
  tkgrid(tklabel(frame1,text="                                             ",font=Env$police),row=0,column=3)
  tkgrid(rb1,row=0,column=5,sticky="w")
  tkgrid(tklabel(frame1,text=Env$vocab[47,1],font=Env$police),row=1,column=1,sticky="e")
  tkgrid(fact.choose,row=1,column=2)
  tkgrid(tklabel(frame1,text=Env$vocab[50,1],font=Env$police),row=1,column=4)
  tkgrid(rb2,row=1,column=5,sticky="w")
  tkgrid(niv.lab,row=2,column=1,sticky="e")
  tkgrid(niv.choose,row=2,column=2)
  tkgrid(rb3,row=2,column=5,sticky="w")
  tkpack(frame1)
  frame2=tkframe(frametot)
  tkgrid(tklabel(frame2,text=" ",font=tkfont.create(family="Arial",size=4)))
  tkgrid(tklabel(frame2,image=tkimage.create("photo",file=file.path(.path.package("GrapheR"),"images",Env$images[15,1],fsep=.Platform$file.sep)),width=800,height=21))
  tkpack(frame2)
  frame3=tkframe(frametot)																	# Fenêtre 5 - frame 3 : titre
  titreValue=tclVar("")
  titre=tkentry(frame3,width=30,font=Env$police,textvariable=titreValue)
  col.titre=tclVar("black")
  col.titre.choose=tkbutton(frame3,text="Aa",font=tkfont.create(family="Arial",size=10,weight="bold"),command=function() {couleur(fen=Fen5,titre=55,var=col.titre,widg=col.titre.choose,type="but",plusieurs=FALSE)})
  taille.titre=tclVar("1.5")
  taille.titre.choose=tkscale(frame3,from=0.5,to=4,showvalue=TRUE,font=Env$police,variable=taille.titre,resolution=0.1,orient="horizontal")
  tkgrid(tklabel(frame3,text=Env$vocab[54,1],font=Env$police),row=0,column=1)
  tkgrid(titre,row=0,column=2)
  tkgrid(tklabel(frame3,text="                             ",font=Env$police),row=0,column=3)
  tkgrid(tklabel(frame3,text=Env$vocab[56,1],font=Env$police),row=0,column=4)
  tkgrid(col.titre.choose,row=0,column=5)
  tkgrid(tklabel(frame3,text="                             ",font=Env$police),row=0,column=6)
  tkgrid(tklabel(frame3,text=Env$vocab[57,1],font=Env$police),row=0,column=7)
  tkgrid(taille.titre.choose,row=0,column=8)
  tkpack(frame3)
  frame4=tkframe(frametot)
  tkgrid(tklabel(frame4,text=" ",font=tkfont.create(family="Arial",size=4)))
  tkgrid(tklabel(frame4,image=tkimage.create("photo",file=file.path(.path.package("GrapheR"),"images",Env$images[16,1],fsep=.Platform$file.sep)),width=800,height=21))
  tkpack(frame4)
  frame5=tkframe(frametot)																	# Fenêtre 5 - frame 5 : axes
  col.axes=tclVar("black")
  col.axes.choose=tkbutton(frame5,text="Aa",font=tkfont.create(family="Arial",size=10,weight="bold"),command=function() {couleur(fen=Fen5,titre=87,var=col.axes,widg=col.axes.choose,type="but",plusieurs=FALSE)})
  col.legendes=tclVar("black")
  col.legendes.choose=tkbutton(frame5,text="Aa",font=tkfont.create(family="Arial",size=10,weight="bold"),command=function() {couleur(fen=Fen5,titre=62,var=col.legendes,widg=col.legendes.choose,type="but",plusieurs=FALSE)})
  taille.axes=tclVar("1")
  taille.axes.choose=tkscale(frame5,from=0.5,to=4,showvalue=TRUE,font=Env$police,variable=taille.axes,resolution=0.1,orient="horizontal")
  taille.legendes=tclVar("1")
  taille.legendes.choose=tkscale(frame5,from=0.5,to=4,showvalue=TRUE,font=Env$police,variable=taille.legendes,resolution=0.1,orient="horizontal")
  xlegendeValue=tclVar("")
  x.legende=tkentry(frame5,width=20,font=Env$police,textvariable=xlegendeValue)
  xinfValue=tclVar("Auto")
  x.inf=tkentry(frame5,width=5,font=Env$police,textvariable=xinfValue)
  xsupValue=tclVar("Auto")
  x.sup=tkentry(frame5,width=5,font=Env$police,textvariable=xsupValue)
  ylegendeValue=tclVar("")
  y.legende=tkentry(frame5,width=20,font=Env$police,textvariable=ylegendeValue)
  ysupValue=tclVar("Auto")
  y.sup=tkentry(frame5,width=5,font=Env$police,textvariable=ysupValue)
  tkgrid(tklabel(frame5,text=Env$vocab[58,1],font=Env$police),row=0,column=1,sticky="e")
  tkgrid(col.axes.choose,row=0,column=2,sticky="w")
  tkgrid(tklabel(frame5,text="                                              ",font=Env$police),row=0,column=3)
  tkgrid(tklabel(frame5,text=Env$vocab[60,1],font=Env$police),row=0,column=4,sticky="se")
  tkgrid(taille.axes.choose,row=0,column=5,sticky="w")
  tkgrid(tklabel(frame5,text=Env$vocab[61,1],font=Env$police),row=1,column=1,sticky="e")
  tkgrid(col.legendes.choose,row=1,column=2,sticky="w")
  tkgrid(tklabel(frame5,text=Env$vocab[63,1],font=Env$police),row=1,column=4,sticky="se")
  tkgrid(taille.legendes.choose,row=1,column=5,sticky="w")
  tkgrid(tklabel(frame5,text="",font=tkfont.create(family="Arial",size=6)))
  tkgrid(tklabel(frame5,text=Env$vocab[64,1],font=tkfont.create(family="Arial",size=10,weight="bold")),row=3,column=1,columnspan=2)
  tkgrid(tklabel(frame5,text=Env$vocab[65,1],font=tkfont.create(family="Arial",size=10,weight="bold")),row=3,column=4,columnspan=2)
  tkgrid(tklabel(frame5,text="",font=tkfont.create(family="Arial",size=3)))
  tkgrid(tklabel(frame5,text=Env$vocab[54,1],font=Env$police),row=5,column=1,sticky="e")
  tkgrid(x.legende,row=5,column=2,sticky="w")
  tkgrid(tklabel(frame5,text=Env$vocab[54,1],font=Env$police),row=5,column=4,sticky="e")
  tkgrid(y.legende,row=5,column=5,sticky="w")
  tkgrid(tklabel(frame5,text=Env$vocab[67,1],font=Env$police),row=6,column=1,sticky="e")
  tkgrid(x.inf,row=6,column=2,sticky="w")
  tkgrid(tklabel(frame5,text=Env$vocab[67,1],font=Env$police),row=6,column=4,sticky="e")
  tkgrid(tklabel(frame5,text="0"),row=6,column=5,sticky="w")
  tkgrid(tklabel(frame5,text=Env$vocab[68,1],font=Env$police),row=7,column=1,sticky="e")
  tkgrid(x.sup,row=7,column=2,sticky="w")
  tkgrid(tklabel(frame5,text=Env$vocab[68,1],font=Env$police),row=7,column=4,sticky="e")
  tkgrid(y.sup,row=7,column=5,sticky="w")
  tkpack(frame5)
  frame6=tkframe(frametot)
  tkgrid(tklabel(frame6,text=" ",font=tkfont.create(family="Arial",size=4)))
  tkgrid(tklabel(frame6,image=tkimage.create("photo",file=file.path(.path.package("GrapheR"),"images",Env$images[17,1],fsep=.Platform$file.sep)),width=800,height=21))
  tkpack(frame6)
  frame7=tkframe(frametot)																	# Fenêtre 5 - frame 7 : barres
  nbbarresValue=tclVar("Auto")
  nb.barres=tkentry(frame7,width=5,font=Env$police,textvariable=nbbarresValue)
  col.barres=tclVar("white")
  col.barres.choose=tkcanvas(frame7,width="25",height="20",bg=tclvalue(col.barres))
  tkbind(col.barres.choose,"<ButtonRelease-1>",function() {couleur(fen=Fen5,titre=113,var=col.barres,widg=col.barres.choose,type="can",plusieurs=FALSE)})
  col.bordures=tclVar("black")
  col.bordures.choose=tkcanvas(frame7,width="25",height="20",bg=tclvalue(col.bordures))
  tkbind(col.bordures.choose,"<ButtonRelease-1>",function() {couleur(fen=Fen5,titre=95,var=col.bordures,widg=col.bordures.choose,type="can",plusieurs=FALSE)})
  tkgrid(tklabel(frame7,text=Env$vocab[69,1],font=Env$police),row=0,column=1,sticky="e")
  tkgrid(nb.barres,row=0,column=2,sticky="w")
  tkgrid(tklabel(frame7,text="                        ",font=Env$police),row=0,column=3)
  tkgrid(tklabel(frame7,text=Env$vocab[70,1],font=Env$police),row=0,column=4,sticky="e")
  tkgrid(col.barres.choose,row=0,column=5,sticky="w")
  tkgrid(tklabel(frame7,text="                        ",font=Env$police),row=0,column=6)
  tkgrid(tklabel(frame7,text=Env$vocab[71,1],font=Env$police),row=0,column=7,sticky="e")
  tkgrid(col.bordures.choose,row=0,column=8,sticky="w")
  tkpack(frame7)
  frame8=tkframe(frametot)
  tkgrid(tklabel(frame8,text=" ",font=tkfont.create(family="Arial",size=4)))
  tkgrid(tklabel(frame8,image=tkimage.create("photo",file=file.path(.path.package("GrapheR"),"images",Env$images[18,1],fsep=.Platform$file.sep)),width=800,height=21))
  tkpack(frame8)
  frame9=tkframe(frametot)																	# Fenêtre 5 - frame 9 : courbe de distribution
  distrib.lab=tklabel(frame9,text=Env$vocab[72,1],font=Env$police,foreground="grey")
  distribValue=tclVar("0")
  distrib.check=tkcheckbutton(frame9)
  tkconfigure(distrib.check,variable=distribValue,state="disabled")
  col.distrib.lab=tklabel(frame9,text=Env$vocab[56,1],font=Env$police,foreground="grey")
  col.distrib=tclVar("grey")
  col.distrib.choose=tkcanvas(frame9,width="25",height="20",bg=tclvalue(col.distrib))
  tkbind(col.distrib.choose,"<ButtonRelease-1>",function() {couleur(fen=Fen5,titre=73,var=col.distrib,widg=col.distrib.choose,type="can",plusieurs=FALSE)})
  type.distrib.lab=tklabel(frame9,text=Env$vocab[74,1],font=Env$police,foreground="grey")
  type.distribValue=tclVar(Env$vocab[75,1])
  type.distrib.choose=ttkcombobox(frame9,font=Env$police,values=c(Env$vocab[75,1],Env$vocab[76,1],Env$vocab[77,1]),width=15,textvariable=type.distribValue,state="disabled")
  ep.distrib.lab=tklabel(frame9,text=if(Env$lang=="fr") {"Epaisseur :   "} else {"Width:   "},font=Env$police,foreground="grey")
  ep.distribValue=tclVar("1")
  ep.distrib.choose=tkscale(frame9,from=1,to=5,showvalue=TRUE,font=Env$police,foreground="grey",length=80,variable=ep.distribValue,resolution=1,orient="horizontal",state="disabled")
  tkgrid(distrib.lab,row=0,column=1)
  tkgrid(distrib.check,row=0,column=2)
  tkgrid(tklabel(frame9,text="         ",font=Env$police),row=0,column=3)
  tkgrid(col.distrib.lab,row=0,column=4)
  tkgrid(col.distrib.choose,row=0,column=5)
  tkgrid(tklabel(frame9,text="         ",font=Env$police),row=0,column=6)
  tkgrid(type.distrib.lab,row=0,column=7)
  tkgrid(type.distrib.choose,row=0,column=8)
  tkgrid(tklabel(frame9,text="         ",font=Env$police),row=0,column=9)
  tkgrid(ep.distrib.lab,row=0,column=10)
  tkgrid(ep.distrib.choose,row=0,column=11)
  tkpack(frame9)
  frame10=tkframe(frametot)
  tkgrid(tklabel(frame10,text="",font=tkfont.create(family="Arial",size=8)))
  tkpack(frame10)
  frame11=tkframe(frametot)																	# Fenêtre 5 - frame 11 : boutons
  tracer=tkbutton(frame11,text=Env$vocab[79,1],font=Env$police,width=25,command=function() {tracer.hist(var=tclvalue(varValue),fact=tclvalue(factValue),
    niv=tclvalue(nivValue),type=tclvalue(typeValue),xinf=tclvalue(xinfValue),xsup=tclvalue(xsupValue),
    ysup=tclvalue(ysupValue),nb.barres=tclvalue(nbbarresValue),col.bar=tclvalue(col.barres),col.bor=tclvalue(col.bordures),x.leg=tclvalue(xlegendeValue),
    y.leg=tclvalue(ylegendeValue),size.leg=as.numeric(tclvalue(taille.legendes)),col.leg=tclvalue(col.legendes),titre=tclvalue(titreValue),col.titre=tclvalue(col.titre),
    size.titre=as.numeric(tclvalue(taille.titre)),col.ax=tclvalue(col.axes),size.ax=as.numeric(tclvalue(taille.axes)),distrib=as.numeric(tclvalue(distribValue)),
    col.distrib=tclvalue(col.distrib),type.distrib=tclvalue(type.distribValue),ep.distrib=as.numeric(tclvalue(ep.distribValue)),fen=Fen5)})
  fenetre=tkbutton(frame11,text=Env$vocab[80,1],font=Env$police,width=25,command=function() {new.window()})
  retour=tkbutton(frame11,text=Env$vocab[81,1],font=Env$police,width=25,command=function() {back(fen=Fen5)})
  tkgrid(tracer,row=0,column=1)
  tkgrid(tklabel(frame11,text="                  ",font=Env$police),row=0,column=2)
  tkgrid(fenetre,row=0,column=3)
  tkgrid(tklabel(frame11,text="                  ",font=Env$police),row=0,column=4)
  tkgrid(retour,row=0,column=5)
  tkgrid(tklabel(frame11,text=" ",font=tkfont.create(family="Arial",size=3)))
  tkpack(frame11)
  tkpack(frametot)
}

