moustaches <-
function() {
  tkwm.withdraw(Env$Fen4)
  Fen6=tktoplevel()
  tktitle(Fen6)="GrapheR"
  tkwm.resizable(Fen6,FALSE,FALSE)
  tcl("wm","protocol",Fen6,"WM_DELETE_WINDOW",function() {if (Env$toolbar.GrapheR==1) {tkdestroy(Env$Toolbar);assign("toolbar.GrapheR",0,pos=Env)};tkdestroy(Fen6);tkdestroy(Env$Fen4);tkdestroy(Env$Fen1)})
  frametot=tkframe(Fen6)
  frame0=tkframe(frametot)
  tkgrid(tklabel(frame0,image=tkimage.create("photo",file=file.path(.path.package("GrapheR"),"images",Env$images[10,1],fsep=.Platform$file.sep)),width=800,height=40))
  tkpack(frame0)
  frame1=tkframe(frametot)												# Fenêtre 6 - frame 1 : généralités
  varValue=tclVar("")
  var.choose=ttkcombobox(frame1,font=Env$police,values=names(Env$datas.GrapheR[which(Env$variables=="N")]),textvariable=varValue,state="readonly")
  factValue=tclVar("")
  fact.choose=ttkcombobox(frame1,font=Env$police,values=names(Env$datas.GrapheR[which(Env$variables=="F")]),textvariable=factValue,state="readonly")
  tkbind(fact.choose,"<<ComboboxSelected>>",function() {moustaches.fact(factValue=factValue)})
  rb1=tkradiobutton(frame1,font=Env$police)
  rb2=tkradiobutton(frame1,font=Env$police)
  orientValue=tclVar("ver")
  tkconfigure(rb1,variable=orientValue,value="ver",text=Env$vocab[84,1])
  tkconfigure(rb2,variable=orientValue,value="hor",text=Env$vocab[85,1])
  tkgrid(tklabel(frame1,text=Env$vocab[46,1],font=Env$police),row=0,column=1,sticky="e")
  tkgrid(var.choose,row=0,column=2)
  tkgrid(tklabel(frame1,text="                                                        ",font=Env$police),row=0,column=3)
  tkgrid(tklabel(frame1,text=Env$vocab[83,1],font=Env$police),row=0,column=4,rowspan=2,sticky="ns")
  tkgrid(rb1,row=0,column=5,sticky="w")
  tkgrid(tklabel(frame1,text=Env$vocab[82,1],font=Env$police),row=1,column=1,sticky="e")
  tkgrid(fact.choose,row=1,column=2)
  tkgrid(rb2,row=1,column=5,sticky="w")
  tkpack(frame1)
  frame2=tkframe(frametot)
  tkgrid(tklabel(frame2,text=" ",font=tkfont.create(family="Arial",size=4)))
  tkgrid(tklabel(frame2,image=tkimage.create("photo",file=file.path(.path.package("GrapheR"),"images",Env$images[15,1],fsep=.Platform$file.sep)),width=800,height=21))
  tkpack(frame2)
  frame3=tkframe(frametot)												# Fenêtre 6 - frame 3 : titre
  titreValue=tclVar("")
  titre=tkentry(frame3,width=30,font=Env$police,textvariable=titreValue)
  col.titre=tclVar("black")
  col.titre.choose=tkbutton(frame3,text="Aa",font=tkfont.create(family="Arial",size=10,weight="bold"),command=function() {couleur(fen=Fen6,titre=55,var=col.titre,widg=col.titre.choose,type="but",plusieurs=FALSE)})
  taille.titre=tclVar("1.5")
  taille.titre.choose=tkscale(frame3,from=0.5,to=4,showvalue=TRUE,font=Env$police,variable=taille.titre,resolution=0.1,orient="horizontal")
  tkgrid(tklabel(frame3,text="          ",font=Env$police),row=0,column=0)
  tkgrid(tklabel(frame3,text=Env$vocab[54,1],font=Env$police),row=0,column=1)
  tkgrid(titre,row=0,column=2)
  tkgrid(tklabel(frame3,text="                             ",font=Env$police),row=0,column=3)
  tkgrid(tklabel(frame3,text=Env$vocab[56,1],font=Env$police),row=0,column=4)
  tkgrid(col.titre.choose,row=0,column=5)
  tkgrid(tklabel(frame3,text="                             ",font=Env$police),row=0,column=6)
  tkgrid(tklabel(frame3,text=Env$vocab[57,1],font=Env$police),row=0,column=7)
  tkgrid(taille.titre.choose,row=0,column=8)
  tkgrid(tklabel(frame3,text="          ",font=Env$police),row=0,column=9)
  tkpack(frame3)
  frame4=tkframe(frametot)
  tkgrid(tklabel(frame4,text=" ",font=tkfont.create(family="Arial",size=4)))
  tkgrid(tklabel(frame4,image=tkimage.create("photo",file=file.path(.path.package("GrapheR"),"images",Env$images[16,1],fsep=.Platform$file.sep)),width=800,height=21))
  tkpack(frame4)
  frame5=tkframe(frametot)												# Fenêtre 6 - frame 5 : axes
  col.axes=tclVar("black")
  col.axes.choose=tkbutton(frame5,text="Aa",font=tkfont.create(family="Arial",size=10,weight="bold"),command=function() {couleur(fen=Fen6,titre=87,var=col.axes,widg=col.axes.choose,type="but",plusieurs=FALSE)})
  col.legendes=tclVar("black")
  col.legendes.choose=tkbutton(frame5,text="Aa",font=tkfont.create(family="Arial",size=10,weight="bold"),command=function() {couleur(fen=Fen6,titre=62,var=col.legendes,widg=col.legendes.choose,type="but",plusieurs=FALSE)})
  taille.axes=tclVar("1")
  taille.axes.choose=tkscale(frame5,from=0.5,to=4,showvalue=TRUE,font=Env$police,variable=taille.axes,resolution=0.1,orient="horizontal")
  taille.legendes=tclVar("1")
  taille.legendes.choose=tkscale(frame5,from=0.5,to=4,showvalue=TRUE,font=Env$police,variable=taille.legendes,resolution=0.1,orient="horizontal")
  xlegendeValue=tclVar("")
  x.legende=tkentry(frame5,width=20,font=Env$police,textvariable=xlegendeValue)
  nom.boites.but=tkbutton(frame5,text=Env$vocab[111,1],font=Env$police,width=16,command=function() {noms1(type="box",fact=tclvalue(factValue),noms=Env$noms1)})
  ylegendeValue=tclVar("")
  y.legende=tkentry(frame5,width=20,font=Env$police,textvariable=ylegendeValue)
  yinfValue=tclVar("Auto")
  y.inf=tkentry(frame5,width=5,font=Env$police,textvariable=yinfValue)
  ysupValue=tclVar("Auto")
  y.sup=tkentry(frame5,width=5,font=Env$police,textvariable=ysupValue)
  logValue=tclVar(0)
  log.check=tkcheckbutton(frame5,font=Env$police)
  tkconfigure(log.check,variable=logValue)
  tkgrid(tklabel(frame5,text=Env$vocab[86,1],font=Env$police),row=0,column=1,sticky="e")
  tkgrid(col.axes.choose,row=0,column=2,sticky="w")
  tkgrid(tklabel(frame5,text="                                                 ",font=Env$police),row=0,column=3)
  tkgrid(tklabel(frame5,text=Env$vocab[88,1],font=Env$police),row=0,column=4,sticky="se")
  tkgrid(taille.axes.choose,row=0,column=5,sticky="w")
  tkgrid(tklabel(frame5,text=Env$vocab[61,1],font=Env$police),row=1,column=1,sticky="e")
  tkgrid(col.legendes.choose,row=1,column=2,sticky="w")
  tkgrid(tklabel(frame5,text=Env$vocab[63,1],font=Env$police),row=1,column=4,sticky="se")
  tkgrid(taille.legendes.choose,row=1,column=5,sticky="w")
  tkgrid(tklabel(frame5,text="",font=tkfont.create(family="Arial",size=6)))
  tkgrid(tklabel(frame5,text=Env$vocab[89,1],font=tkfont.create(family="Arial",size=10,weight="bold")),row=3,column=1,columnspan=2)
  tkgrid(tklabel(frame5,text=Env$vocab[90,1],font=tkfont.create(family="Arial",size=10,weight="bold")),row=3,column=4,columnspan=2)
  tkgrid(tklabel(frame5,text=" ",font=tkfont.create(family="Arial",size=3)))
  tkgrid(tklabel(frame5,text=Env$vocab[54,1],font=Env$police),row=5,column=1,sticky="e")
  tkgrid(x.legende,row=5,column=2,sticky="w")
  tkgrid(tklabel(frame5,text=Env$vocab[54,1],font=Env$police),row=5,column=4,sticky="e")
  tkgrid(y.legende,row=5,column=5,sticky="w")
  tkgrid(tklabel(frame5,text=Env$vocab[91,1],font=Env$police),row=6,column=1,sticky="e")
  tkgrid(nom.boites.but,row=6,column=2,sticky="we")
  tkgrid(tklabel(frame5,text=Env$vocab[67,1],font=Env$police),row=6,column=4,sticky="e")
  tkgrid(y.inf,row=6,column=5,sticky="w")
  tkgrid(tklabel(frame5,text=Env$vocab[68,1],font=Env$police),row=7,column=4,sticky="e")
  tkgrid(y.sup,row=7,column=5,sticky="w")
  tkgrid(tklabel(frame5,text=Env$vocab[92,1],font=Env$police),row=8,column=4,sticky="e")
  tkgrid(log.check,row=8,column=5,sticky="w")
  tkpack(frame5)
  frame6=tkframe(frametot)
  tkgrid(tklabel(frame6,text=" ",font=tkfont.create(family="Arial",size=4)))
  tkgrid(tklabel(frame6,image=tkimage.create("photo",file=file.path(.path.package("GrapheR"),"images",Env$images[19,1],fsep=.Platform$file.sep)),width=800,height=21))
  tkpack(frame6)
  frame7=tkframe(frametot)												# Fenêtre 6 - frame 7 : boîtes
  col.boites=tclVar("white")
  col.boites.choose=tkcanvas(frame7,width="25",height="20",bg=tclvalue(col.boites))
  tkbind(col.boites.choose,"<ButtonRelease-1>",function() {couleur(fen=Fen6,titre=94,var=col.boites,widg=col.boites.choose,type="can",plusieurs=FALSE)})
  col.bordures=tclVar("black")
  col.bordures.choose=tkcanvas(frame7,width="25",height="20",bg=tclvalue(col.bordures))
  tkbind(col.bordures.choose,"<ButtonRelease-1>",function() {couleur(fen=Fen6,titre=95,var=col.bordures,widg=col.bordures.choose,type="can",plusieurs=FALSE)})
  ICvalue=tclVar(0)
  IC.check=tkcheckbutton(frame7,font=Env$police)
  tkconfigure(IC.check,variable=ICvalue)
  tkgrid(tklabel(frame7,text=Env$vocab[93,1],font=Env$police),row=0,column=1,sticky="e")
  tkgrid(col.boites.choose,row=0,column=2,sticky="w")
  tkgrid(tklabel(frame7,text="                            ",font=Env$police),row=0,column=3)
  tkgrid(tklabel(frame7,text=Env$vocab[71,1],font=Env$police),row=0,column=4,sticky="e")
  tkgrid(col.bordures.choose,row=0,column=5,sticky="w")
  tkgrid(tklabel(frame7,text="                            ",font=Env$police),row=0,column=6)
  tkgrid(tklabel(frame7,text=Env$vocab[96,1],font=Env$police),row=0,column=7,sticky="e")
  tkgrid(IC.check,row=0,column=8,sticky="w")
  tkpack(frame7)
  frame8=tkframe(frametot)
  tkgrid(tklabel(frame8,text=" ",font=tkfont.create(family="Arial",size=4)))
  tkgrid(tklabel(frame8,image=tkimage.create("photo",file=file.path(.path.package("GrapheR"),"images",Env$images[20,1],fsep=.Platform$file.sep)),width=800,height=21))
  tkpack(frame8)
  frame9=tkframe(frametot)												# Fenêtre 6 - frame 9 : moustaches
  col.moustaches=tclVar("black")
  col.moustaches.choose=tkcanvas(frame9,width="25",height="20",bg=tclvalue(col.moustaches))
  tkbind(col.moustaches.choose,"<ButtonRelease-1>",function() {couleur(fen=Fen6,titre=98,var=col.moustaches,widg=col.moustaches.choose,type="can",plusieurs=FALSE)})
  taille.moustaches=tclVar("1.5")
  taille.moustaches.choose=tkscale(frame9,from=0,to=3,showvalue=TRUE,font=Env$police,variable=taille.moustaches,resolution=0.1,orient="horizontal")
  moustachesValue=tclVar(Env$vocab[76,1])
  moustaches.choose=ttkcombobox(frame9,font=Env$police,values=c(Env$vocab[75,1],Env$vocab[76,1],Env$vocab[77,1]),textvariable=moustachesValue,state="readonly",width=14)
  tkgrid(tklabel(frame9,text=Env$vocab[97,1],font=Env$police),row=0,column=1,sticky="e")
  tkgrid(col.moustaches.choose,row=0,column=2,sticky="w")
  tkgrid(tklabel(frame9,text="               ",font=Env$police),row=0,column=3)
  tkgrid(tklabel(frame9,text=Env$vocab[99,1],font=Env$police),row=0,column=4,sticky="se")
  tkgrid(taille.moustaches.choose,row=0,column=5,sticky="w")
  tkgrid(tklabel(frame9,text="              ",font=Env$police),row=0,column=6)
  tkgrid(tklabel(frame9,text=Env$vocab[74,1],font=Env$police),row=0,column=7,sticky="e")
  tkgrid(moustaches.choose,row=0,column=8,sticky="w")
  tkpack(frame9)
  frame10=tkframe(frametot)
  tkgrid(tklabel(frame10,text=" ",font=tkfont.create(family="Arial",size=4)))
  tkgrid(tklabel(frame10,image=tkimage.create("photo",file=file.path(.path.package("GrapheR"),"images",Env$images[21,1],fsep=.Platform$file.sep)),width=800,height=21))
  tkpack(frame10)
  frame11=tkframe(frametot)												# Fenêtre 6 - frame 11 : individus extrêmes
  outliers=tclVar(0)
  outliers.check=tkcheckbutton(frame11,font=Env$police,variable=outliers)
  tkselect(outliers.check)
  tkconfigure(outliers.check,variable=outliers)
  col.outliers=tclVar("black")
  col.outliers.choose=tkcanvas(frame11,width="25",height="20",bg=tclvalue(col.outliers))
  tkbind(col.outliers.choose,"<ButtonRelease-1>",function() {couleur(fen=Fen6,titre=101,var=col.outliers,widg=col.outliers.choose,type="can",plusieurs=FALSE)})
  rb3=tkradiobutton(frame11,font=Env$police)
  rb4=tkradiobutton(frame11,font=Env$police)
  symb.outlierValue=tclVar("vide")
  tkconfigure(rb3,variable=symb.outlierValue,value="vide",text=Env$vocab[103,1])
  tkconfigure(rb4,variable=symb.outlierValue,value="plein",text=Env$vocab[104,1])
  tkgrid(tklabel(frame11,text=Env$vocab[100,1],font=Env$police),row=0,column=1,rowspan=2,sticky="e")
  tkgrid(outliers.check,row=0,column=2,rowspan=2,sticky="w")
  tkgrid(tklabel(frame11,text="                               ",font=Env$police),row=0,column=3)
  tkgrid(tklabel(frame11,text=Env$vocab[56,1],font=Env$police),row=0,column=4,rowspan=2,sticky="e")
  tkgrid(col.outliers.choose,row=0,column=5,rowspan=2,sticky="w")
  tkgrid(tklabel(frame11,text="                                       ",font=Env$police),row=0,column=6)
  tkgrid(tklabel(frame11,text=Env$vocab[102,1],font=Env$police),row=0,column=7,rowspan=2,sticky="nse")
  tkgrid(rb3,row=0,column=8,sticky="w")
  tkgrid(rb4,row=1,column=8,sticky="w")
  tkpack(frame11)
  frame12=tkframe(frametot)
  tkgrid(tklabel(frame12,text="",font=tkfont.create(family="Arial",size=8)))
  tkpack(frame12)
  frame13=tkframe(frametot)																	# Fenêtre 6 - frame 13 : boutons
  tracer=tkbutton(frame13,text=Env$vocab[79,1],font=Env$police,width=25,command=function() {tracer.moustaches(var=tclvalue(varValue),fact=tclvalue(factValue),
    orient=tclvalue(orientValue),log.ax=as.numeric(tclvalue(logValue)),yinf=tclvalue(yinfValue),ysup=tclvalue(ysupValue),
    col.box=tclvalue(col.boites),col.bor=tclvalue(col.bordures),col.wsk=tclvalue(col.moustaches),col.out=tclvalue(col.outliers),lty.wsk=tclvalue(moustachesValue),
    out=as.numeric(tclvalue(outliers)),pch.out=tclvalue(symb.outlierValue),size.mous=as.numeric(tclvalue(taille.moustaches)),noms=Env$noms1,ic=as.numeric(tclvalue(ICvalue)),
    x.leg=tclvalue(xlegendeValue),y.leg=tclvalue(ylegendeValue),size.leg=as.numeric(tclvalue(taille.legendes)),col.leg=tclvalue(col.legendes),titre=tclvalue(titreValue),
    col.titre=tclvalue(col.titre),size.titre=as.numeric(tclvalue(taille.titre)),col.ax=tclvalue(col.axes),size.ax=as.numeric(tclvalue(taille.axes)),fen=Fen6)})
  fenetre=tkbutton(frame13,text=Env$vocab[80,1],font=Env$police,width=25,command=function() {new.window()})
  retour=tkbutton(frame13,text=Env$vocab[81,1],font=Env$police,width=25,command=function() {back(fen=Fen6)})
  tkgrid(tracer,row=0,column=1)
  tkgrid(tklabel(frame13,text="                  ",font=Env$police),row=0,column=2)
  tkgrid(fenetre,row=0,column=3)
  tkgrid(tklabel(frame13,text="                  ",font=Env$police),row=0,column=4)
  tkgrid(retour,row=0,column=5)
  tkgrid(tklabel(frame13,text="",font=tkfont.create(family="Arial",size=3)))
  tkpack(frame13)
  tkpack(frametot)
}

