nuage <-
function() {
  tkwm.withdraw(Env$Fen4)
  Fen23=tktoplevel()
  tktitle(Fen23)="GrapheR"
  tkwm.resizable(Fen23,FALSE,FALSE)
  tcl("wm","protocol",Fen23,"WM_DELETE_WINDOW",function() {if (Env$toolbar.GrapheR==1) {tkdestroy(Env$Toolbar);assign("toolbar.GrapheR",0,pos=Env)};tkdestroy(Fen23);tkdestroy(Env$Fen4);tkdestroy(Env$Fen1)})
  frametot=tkframe(Fen23)
  frame0=tkframe(frametot)
  tkgrid(tklabel(frame0,image=tkimage.create("photo",file=file.path(.path.package("GrapheR"),"images",Env$images[14,1],fsep=.Platform$file.sep)),width=800,height=40))
  tkpack(frame0)
  frame1=tkframe(frametot)																	# Fenêtre 23 - frame 1 : généralités
  var1Value=tclVar()
  var1.choose=ttkcombobox(frame1,font=Env$police,values=names(Env$datas.GrapheR[which(Env$variables=="N")]),textvariable=var1Value,state="readonly")
  var2Value=tclVar()
  var2.choose=ttkcombobox(frame1,font=Env$police,values=names(Env$datas.GrapheR[which(Env$variables=="N")]),textvariable=var2Value,state="readonly")
  factValue=tclVar()
  fact.choose=ttkcombobox(frame1,font=Env$police,values=c(Env$vocab[48,1],names(Env$datas.GrapheR[which(Env$variables=="F")])),textvariable=factValue,state="readonly")
  assign("niv.fact","",pos=Env)
  assign("symb",1,pos=Env)
  assign("col.str1","black",pos=Env)
  assign("droite","aucune",pos=Env)
  assign("regression","mc",pos=Env)
  assign("hor","",pos=Env)
  assign("ver","",pos=Env)
  assign("coeffa","",pos=Env)
  assign("coeffb","",pos=Env)
  assign("traits",Env$vocab[75,1],pos=Env)
  assign("ep.lignes","1",pos=Env)
  assign("legende.titre","",pos=Env)
  tkbind(fact.choose,"<<ComboboxSelected>>",function() {nuage.fact(factValue=factValue,niv.but=niv.but,legende.check.lab=legende.check.lab,legende.check=legende.check,nom.legende.lab=nom.legende.lab,
    nom.legende.but=nom.legende.but,legende.pos.lab=legende.pos.lab,legende.pos.choose=legende.pos.choose)})
  niv.but=tkbutton(frame1,text=Env$vocab[111,1],font=Env$police,width=16,state="disabled",command=function() {niv(fact=tclvalue(factValue),niv=Env$niv.fact)})
  boxValue=tclVar("0")
  box.check=tkcheckbutton(frame1,font=Env$police)
  tkconfigure(box.check,variable=boxValue)
  tkgrid(tklabel(frame1,text=Env$vocab[146,1],font=Env$police),row=0,column=1,sticky="e")
  tkgrid(var1.choose,row=0,column=2)
  tkgrid(tklabel(frame1,text="                    ",font=Env$police),row=0,column=3)
  tkgrid(tklabel(frame1,text=Env$vocab[47,1],font=Env$police),row=0,column=4,sticky="e")
  tkgrid(fact.choose,row=0,column=5,sticky="w")
  tkgrid(tklabel(frame1,text="                    ",font=Env$police),row=0,column=7)
  tkgrid(tklabel(frame1,text=Env$vocab[147,1],font=Env$police),row=1,column=1,sticky="e")
  tkgrid(var2.choose,row=1,column=2,sticky="w")
  tkgrid(tklabel(frame1,text=Env$vocab[155,1],font=Env$police),row=1,column=4,sticky="e")
  tkgrid(niv.but,row=1,column=5)
  tkgrid(tklabel(frame1,text=Env$vocab[151,1],font=Env$police),row=0,column=8,rowspan=2,sticky="e")
  tkgrid(box.check,row=0,column=9,rowspan=2,sticky="w")
  tkpack(frame1)
  frame2=tkframe(frametot)
  tkgrid(tklabel(frame2,text=" ",font=tkfont.create(family="Arial",size=4)))
  tkgrid(tklabel(frame2,image=tkimage.create("photo",file=file.path(.path.package("GrapheR"),"images",Env$images[15,1],fsep=.Platform$file.sep)),width=800,height=21))
  tkpack(frame2)
  frame3=tkframe(frametot)																	# Fenêtre 23 - frame 3 : titre
  titreValue=tclVar("")
  titre=tkentry(frame3,width=30,font=Env$police,textvariable=titreValue)
  col.titre=tclVar("black")
  col.titre.choose=tkbutton(frame3,text="Aa",font=tkfont.create(family="Arial",size=10,weight="bold"),command=function() {couleur(fen=Fen23,titre=55,var=col.titre,widg=col.titre.choose,type="but",plusieurs=FALSE)})
  taille.titre=tclVar("1.5")
  taille.titre.choose=tkscale(frame3,from=0.5,to=4,showvalue=TRUE,font=Env$police,variable=taille.titre,resolution=0.1,orient="horizontal")
  tkgrid(tklabel(frame3,text=Env$vocab[54,1],font=Env$police),row=0,column=1)
  tkgrid(titre,row=0,column=2)
  tkgrid(tklabel(frame3,text="                             ",font=Env$police),row=0,column=3)
  tkgrid(tklabel(frame3,text=Env$vocab[56,1],font=Env$police),row=0,column=4)
  tkgrid(col.titre.choose,row=0,column=5)
  tkgrid(tklabel(frame3,text="                             ",font=Env$police),row=0,column=6)
  tkgrid(tklabel(frame3,text=Env$vocab[57,1],font=Env$police),row=0,column=7)
  tkgrid(taille.titre.choose,row=0,column=8)
  tkpack(frame3)
  frame4=tkframe(frametot)
  tkgrid(tklabel(frame4,text=" ",font=tkfont.create(family="Arial",size=4)))
  tkgrid(tklabel(frame4,image=tkimage.create("photo",file=file.path(.path.package("GrapheR"),"images",Env$images[16,1],fsep=.Platform$file.sep)),width=800,height=21))
  tkpack(frame4)
  frame5=tkframe(frametot)																	# Fenêtre 23 - frame 5 : axes
  col.axes=tclVar("black")
  col.axes.choose=tkbutton(frame5,text="Aa",font=tkfont.create(family="Arial",size=10,weight="bold"),command=function() {couleur(fen=Fen23,titre=59,var=col.axes,widg=col.axes.choose,type="but",plusieurs=FALSE)})
  col.legendes=tclVar("black")
  col.legendes.choose=tkbutton(frame5,text="Aa",font=tkfont.create(family="Arial",size=10,weight="bold"),command=function() {couleur(fen=Fen23,titre=62,var=col.legendes,widg=col.legendes.choose,type="but",plusieurs=FALSE)})
  taille.axes=tclVar("1")
  taille.axes.choose=tkscale(frame5,from=0.5,to=4,showvalue=TRUE,font=Env$police,variable=taille.axes,resolution=0.1,orient="horizontal")
  taille.legendes=tclVar("1")
  taille.legendes.choose=tkscale(frame5,from=0.5,to=4,showvalue=TRUE,font=Env$police,variable=taille.legendes,resolution=0.1,orient="horizontal")
  xlegendeValue=tclVar("")
  x.legende=tkentry(frame5,width=20,font=Env$police,textvariable=xlegendeValue)
  xinfValue=tclVar("Auto")
  x.inf=tkentry(frame5,width=5,font=Env$police,textvariable=xinfValue)
  xsupValue=tclVar("Auto")
  x.sup=tkentry(frame5,width=5,font=Env$police,textvariable=xsupValue)
  xlogValue=tclVar("0")
  xlog.check=tkcheckbutton(frame5,font=Env$police)
  tkconfigure(xlog.check,variable=xlogValue)
  ylegendeValue=tclVar("")
  y.legende=tkentry(frame5,width=20,font=Env$police,textvariable=ylegendeValue)
  yinfValue=tclVar("Auto")
  y.inf=tkentry(frame5,width=5,font=Env$police,textvariable=yinfValue)
  ysupValue=tclVar("Auto")
  y.sup=tkentry(frame5,width=5,font=Env$police,textvariable=ysupValue)
  ylogValue=tclVar("0")
  ylog.check=tkcheckbutton(frame5,font=Env$police)
  tkconfigure(ylog.check,variable=ylogValue)
  tkgrid(tklabel(frame5,text=Env$vocab[58,1],font=Env$police),row=0,column=1,sticky="e")
  tkgrid(col.axes.choose,row=0,column=2,sticky="w")
  tkgrid(tklabel(frame5,text="                                              ",font=Env$police),row=0,column=3)
  tkgrid(tklabel(frame5,text=Env$vocab[60,1],font=Env$police),row=0,column=4,sticky="se")
  tkgrid(taille.axes.choose,row=0,column=5,sticky="w")
  tkgrid(tklabel(frame5,text=Env$vocab[61,1],font=Env$police),row=1,column=1,sticky="e")
  tkgrid(col.legendes.choose,row=1,column=2,sticky="w")
  tkgrid(tklabel(frame5,text=Env$vocab[63,1],font=Env$police),row=1,column=4,sticky="se")
  tkgrid(taille.legendes.choose,row=1,column=5,sticky="w")
  tkgrid(tklabel(frame5,text="",font=tkfont.create(family="Arial",size=6)))
  tkgrid(tklabel(frame5,text=Env$vocab[64,1],font=tkfont.create(family="Arial",size=10,weight="bold")),row=3,column=1,columnspan=2)
  tkgrid(tklabel(frame5,text=Env$vocab[65,1],font=tkfont.create(family="Arial",size=10,weight="bold")),row=3,column=4,columnspan=2)
  tkgrid(tklabel(frame5,text="",font=tkfont.create(family="Arial",size=3)))
  tkgrid(tklabel(frame5,text=Env$vocab[54,1],font=Env$police),row=5,column=1,sticky="e")
  tkgrid(x.legende,row=5,column=2,sticky="w")
  tkgrid(tklabel(frame5,text=Env$vocab[54,1],font=Env$police),row=5,column=4,sticky="e")
  tkgrid(y.legende,row=5,column=5,sticky="w")
  tkgrid(tklabel(frame5,text=Env$vocab[67,1],font=Env$police),row=6,column=1,sticky="e")
  tkgrid(x.inf,row=6,column=2,sticky="w")
  tkgrid(tklabel(frame5,text=Env$vocab[67,1],font=Env$police),row=6,column=4,sticky="e")
  tkgrid(y.inf,row=6,column=5,sticky="w")
  tkgrid(tklabel(frame5,text=Env$vocab[68,1],font=Env$police),row=7,column=1,sticky="e")
  tkgrid(x.sup,row=7,column=2,sticky="w")
  tkgrid(tklabel(frame5,text=Env$vocab[68,1],font=Env$police),row=7,column=4,sticky="e")
  tkgrid(y.sup,row=7,column=5,sticky="w")
  tkgrid(tklabel(frame5,text=Env$vocab[92,1],font=Env$police),row=8,column=1,sticky="e")
  tkgrid(xlog.check,row=8,column=2,sticky="w")
  tkgrid(tklabel(frame5,text=Env$vocab[92,1],font=Env$police),row=8,column=4,sticky="e")
  tkgrid(ylog.check,row=8,column=5,sticky="w")
  tkpack(frame5)
  frame6=tkframe(frametot)
  tkgrid(tklabel(frame6,text=" ",font=tkfont.create(family="Arial",size=4)))
  tkgrid(tklabel(frame6,image=tkimage.create("photo",file=file.path(.path.package("GrapheR"),"images",Env$images[28,1],fsep=.Platform$file.sep)),width=800,height=21))
  tkpack(frame6)
  frame7=tkframe(frametot)																	# Fenêtre 23 - frame 7 : points et courbes
  symb.but=tkbutton(frame7,text=Env$vocab[152,1],font=Env$police,width=25,command=function() {nuage.symbol(factValue=factValue)})
  taille.pt=tclVar("1")
  taille.pt.choose=tkscale(frame7,from=0.3,to=3,showvalue=TRUE,font=Env$police,variable=taille.pt,resolution=0.1,orient="horizontal")
  courbe.but=tkbutton(frame7,text=Env$vocab[156,1],font=Env$police,width=25,command=function() {nuage.droite(var1Value=var1Value,var2Value=var2Value,factValue=factValue)})
  tkgrid(symb.but,row=0,column=1)
  tkgrid(tklabel(frame7,text="                        ",font=Env$police),row=0,column=2)
  tkgrid(tklabel(frame7,text=Env$vocab[153,1],font=Env$police),row=0,column=3,sticky="e")
  tkgrid(taille.pt.choose,row=0,column=4,sticky="w")
  tkgrid(tklabel(frame7,text="                        ",font=Env$police),row=0,column=5)
  tkgrid(courbe.but,row=0,column=6)
  tkpack(frame7)
  frame8=tkframe(frametot)
  tkgrid(tklabel(frame8,text=" ",font=tkfont.create(family="Arial",size=4)))
  tkgrid(tklabel(frame8,image=tkimage.create("photo",file=file.path(.path.package("GrapheR"),"images",Env$images[26,1],fsep=.Platform$file.sep)),width=800,height=21))
  tkpack(frame8)
  frame9=tkframe(frametot)																	# Fenêtre 23 - frame 9 : légende
  legende.check.lab=tklabel(frame9,text=Env$vocab[66,1],foreground="grey",font=Env$police)
  legendeValue=tclVar("0")
  legende.check=tkcheckbutton(frame9,font=Env$police,variable=legendeValue)
  tkconfigure(legende.check,variable=legendeValue,state="disabled")
  nom.legende.lab=tklabel(frame9,text=Env$vocab[124,1],foreground="grey",font=Env$police)
  nom.legende.but=tkbutton(frame9,text=Env$vocab[111,1],font=Env$police,width=16,state="disabled",command=function() {legende(type="nuage",nb.niv=Env$nb.niv1,noms=Env$noms1,titre=Env$legende.titre)})
  legende.pos.lab=tklabel(frame9,text=Env$vocab[125,1],foreground="grey",font=Env$police)
  legende.posValue=tclVar(Env$vocab[126,1])
  legende.pos.choose=ttkcombobox(frame9,font=Env$police,values=c(Env$vocab[126,1],Env$vocab[127,1],Env$vocab[128,1],Env$vocab[129,1],Env$vocab[130,1],Env$vocab[131,1],Env$vocab[132,1],Env$vocab[133,1],Env$vocab[134,1]),textvariable=legende.posValue,state="readonly",state="disabled")
  tkgrid(legende.check.lab,row=0,column=1,sticky="e")
  tkgrid(legende.check,row=0,column=2,sticky="w")
  tkgrid(tklabel(frame9,text="                            ",font=Env$police),row=0,column=3)
  tkgrid(nom.legende.lab,row=0,column=4,sticky="e")
  tkgrid(nom.legende.but,row=0,column=5,sticky="w")
  tkgrid(tklabel(frame9,text="                       ",font=Env$police),row=0,column=6)
  tkgrid(legende.pos.lab,row=0,column=7,sticky="e")
  tkgrid(legende.pos.choose,row=0,column=8,sticky="w")
  tkpack(frame9)
  frame10=tkframe(frametot)
  tkgrid(tklabel(frame10,text="",font=tkfont.create(family="Arial",size=8)))
  tkpack(frame10)
  frame11=tkframe(frametot)																	# Fenêtre 23 - frame 11 : boutons
  tracer=tkbutton(frame11,text=Env$vocab[79,1],font=Env$police,width=25,command=function() {tracer.nuage(var1=tclvalue(var1Value),var2=tclvalue(var2Value),fact=tclvalue(factValue),
    nb.niv=Env$nb.niv1,niv=Env$niv.fact,encadre=as.numeric(tclvalue(boxValue)),titre=tclvalue(titreValue),col.titre=tclvalue(col.titre),taille.titre=as.numeric(tclvalue(taille.titre)),
    col.ax=tclvalue(col.axes),taille.ax=as.numeric(tclvalue(taille.axes)),col.legende=tclvalue(col.legendes),taille.legende=as.numeric(tclvalue(taille.legendes)),x.legende=tclvalue(xlegendeValue),
    y.legende=tclvalue(ylegendeValue),x.inf=tclvalue(xinfValue),x.sup=tclvalue(xsupValue),y.inf=tclvalue(yinfValue),y.sup=tclvalue(ysupValue),x.log=as.numeric(tclvalue(xlogValue)),
    y.log=as.numeric(tclvalue(ylogValue)),symbol=Env$symb,col.symb=Env$col.str1,taille.symb=as.numeric(tclvalue(taille.pt)),drt=Env$droite,reg=Env$regression,horiz=Env$hor,vertic=Env$ver,coefa=Env$coeffa,coefb=Env$coeffb,
    tra=Env$traits,ep.lig=as.numeric(Env$ep.lignes),leg=as.numeric(tclvalue(legendeValue)),pos.leg=tclvalue(legende.posValue),noms=Env$noms1,leg.titre=Env$legende.titre,fen=Fen23)})
  fenetre=tkbutton(frame11,text=Env$vocab[80,1],font=Env$police,width=25,command=function() {new.window()})
  retour=tkbutton(frame11,text=Env$vocab[81,1],font=Env$police,width=25,command=function() {back(fen=Fen23)})
  tkgrid(tracer,row=0,column=1)
  tkgrid(tklabel(frame11,text="                  ",font=Env$police),row=0,column=2)
  tkgrid(fenetre,row=0,column=3)
  tkgrid(tklabel(frame11,text="                  ",font=Env$police),row=0,column=4)
  tkgrid(retour,row=0,column=5)
  tkgrid(tklabel(frame11,text="",font=tkfont.create(family="Arial",size=3)))
  tkpack(frame11)
  tkpack(frametot)
}

