unecourbe <-
function(lig,tra,ep) {
  Fen34=tktoplevel()
  tkwm.resizable(Fen34,FALSE,FALSE)
  tktitle(Fen34)="GrapheR"
  tkgrab.set(Fen34)
  tkfocus(Fen34)
  lig2=tclVar(lig)
  tra2=tclVar(tra)
  ep2=tclVar(ep)
  ligne.choose=ttkcombobox(Fen34,font=Env$police,values=c(Env$vocab[164,1],Env$vocab[165,1],Env$vocab[166,1],Env$vocab[167,1],Env$vocab[168,1]),textvariable=lig2,state="readonly")
  trait.choose=ttkcombobox(Fen34,font=Env$police,values=c(Env$vocab[75,1],Env$vocab[76,1],Env$vocab[77,1]),textvariable=tra2,state="readonly")
  ep.courbe.choose=tkscale(Fen34,from=1,to=5,showvalue=TRUE,font=Env$police,variable=ep2,resolution=1,orient="horizontal")
  ok=tkbutton(Fen34,text=Env$vocab[1,1],font=Env$police,width=16,command=function() {
    assign("lignes",tclvalue(lig2),pos=Env)
    assign("traits",tclvalue(tra2),pos=Env)
    assign("ep.lignes",as.numeric(tclvalue(ep2)),pos=Env)
    tkgrab.release(Fen34)
    tkdestroy(Fen34)
  })
  annuler=tkbutton(Fen34,text=Env$vocab[2,1],font=Env$police,width=16,command=function() {tkgrab.release(Fen34);tkdestroy(Fen34)})
  tkgrid(tklabel(Fen34,text="",font=Env$police))
  tkgrid(tklabel(Fen34,text="     ",font=Env$police),row=1,column=0)
  tkgrid(tklabel(Fen34,text=Env$vocab[163,1],font=Env$police),row=1,column=1,sticky="e")
  tkgrid(ligne.choose,row=1,column=2,sticky="w")
  tkgrid(tklabel(Fen34,text="     ",font=Env$police),row=1,column=3)
  tkgrid(tklabel(Fen34,text="",font=Env$police))
  tkgrid(tklabel(Fen34,text=Env$vocab[74,1],font=Env$police),row=3,column=1,sticky="e")
  tkgrid(trait.choose,row=3,column=2,sticky="w")
  tkgrid(tklabel(Fen34,text=" ",font=tkfont.create(family="Arial",size=1)))
  tkgrid(tklabel(Fen34,text=Env$vocab[78,1],font=Env$police),row=5,column=1,sticky="e")
  tkgrid(ep.courbe.choose,row=5,column=2,sticky="w")
  tkgrid(tklabel(Fen34,text="",font=Env$police))
  tkgrid(ok,column=1,columnspan=2)
  tkgrid(tklabel(Fen34,text=" ",font=tkfont.create(family="Arial",size=4)))
  tkgrid(annuler,column=1,columnspan=2)
  tkgrid(tklabel(Fen34,text=" ",font=tkfont.create(family="Arial",size=4)))
}

