unedroite <-
function(var1,var2,drt,reg,horiz,vertic,coefa,coefb,tra,ep.lig) {
  Fen26=tktoplevel()
  tkwm.resizable(Fen26,FALSE,FALSE)
  tktitle(Fen26)="GrapheR"
  tkgrab.set(Fen26)
  tkfocus(Fen26)
  drt2=tclVar(drt)
  reg2=tclVar(reg)
  horiz2=tclVar(horiz)
  vertic2=tclVar(vertic)
  coefa2=tclVar(coefa)
  coefb2=tclVar(coefb)
  tra2=tclVar(tra)
  ep.lig2=tclVar(ep.lig)
  inactif=function() {
    tkconfigure(rb8,state="disabled")
    tkconfigure(rb9,state="disabled")
    tkconfigure(hor,state="disabled")
    tkconfigure(ver,state="disabled")
    tkconfigure(coeffa,state="disabled")
    tkconfigure(coeffb,state="disabled")
  }
  rb1=tkradiobutton(Fen26,font=Env$police,command=inactif)
  rb2=tkradiobutton(Fen26,font=Env$police,command=function() {inactif();tkconfigure(hor,state="normal")})
  rb3=tkradiobutton(Fen26,font=Env$police,command=function() {inactif();tkconfigure(ver,state="normal")})
  rb4=tkradiobutton(Fen26,font=Env$police,command=function() {inactif();tkconfigure(coeffa,state="normal");tkconfigure(coeffb,state="normal")})
  rb5=tkradiobutton(Fen26,font=Env$police,command=function() {inactif();tkconfigure(rb8,state="normal");tkconfigure(rb9,state="normal")})
  rb6=tkradiobutton(Fen26,font=Env$police,command=inactif)
  rb7=tkradiobutton(Fen26,font=Env$police,command=inactif)
  rb8=tkradiobutton(Fen26,font=Env$police,command=function() {inactif();tkconfigure(rb8,state="normal");tkconfigure(rb9,state="normal")})
  rb9=tkradiobutton(Fen26,font=Env$police,command=function() {inactif();tkconfigure(rb8,state="normal");tkconfigure(rb9,state="normal")})
  tkconfigure(rb1,variable=drt2,value="aucune",text=Env$vocab[118,1])
  tkconfigure(rb2,variable=drt2,value="hor",text=Env$vocab[169,1])
  tkconfigure(rb3,variable=drt2,value="ver",text=Env$vocab[170,1])
  tkconfigure(rb4,variable=drt2,value="affine",text=Env$vocab[171,1])
  tkconfigure(rb5,variable=drt2,value="reg",text=Env$vocab[172,1])
  tkconfigure(rb6,variable=drt2,value="quadra",text=Env$vocab[175,1])
  tkconfigure(rb7,variable=drt2,value="gam",text=Env$vocab[176,1])
  tkconfigure(rb8,variable=reg2,value="mc",text=Env$vocab[173,1],state=if (tclvalue(drt2)=="reg") {"normal"} else {"disabled"})
  tkconfigure(rb9,variable=reg2,value="mr",text=Env$vocab[174,1],state=if (tclvalue(drt2)=="reg") {"normal"} else {"disabled"})
  hor=tkentry(Fen26,width=5,font=Env$police,textvariable=horiz2,state=if (tclvalue(drt2)=="hor") {"normal"} else {"disabled"})
  ver=tkentry(Fen26,width=5,font=Env$police,textvariable=vertic2,state=if (tclvalue(drt2)=="ver") {"normal"} else {"disabled"})
  coeffa=tkentry(Fen26,width=5,font=Env$police,textvariable=coefa2,state=if (tclvalue(drt2)=="affine") {"normal"} else {"disabled"})
  coeffb=tkentry(Fen26,width=5,font=Env$police,textvariable=coefb2,state=if (tclvalue(drt2)=="affine") {"normal"} else {"disabled"})
  trait.choose=ttkcombobox(Fen26,font=Env$police,values=c(Env$vocab[75,1],Env$vocab[76,1],Env$vocab[77,1]),textvariable=tra2,state="readonly")
  ep.choose=tkscale(Fen26,from=1,to=5,showvalue=TRUE,font=Env$police,variable=ep.lig2,resolution=1,orient="horizontal")
  ok=tkbutton(Fen26,text=Env$vocab[1,1],font=Env$police,width=16,command=function() {
    assign("droite",tclvalue(drt2),pos=Env)
    assign("regression",tclvalue(reg2),pos=Env)
    assign("hor",tclvalue(horiz2),pos=Env)
    assign("ver",tclvalue(vertic2),pos=Env)
    assign("coeffa",tclvalue(coefa2),pos=Env)
    assign("coeffb",tclvalue(coefb2),pos=Env)
    assign("traits",tclvalue(tra2),pos=Env)
    assign("ep.lignes",tclvalue(ep.lig2),pos=Env)
    tkgrab.release(Fen26)
    tkdestroy(Fen26)
  })
  annuler=tkbutton(Fen26,text=Env$vocab[2,1],font=Env$police,width=16,command=function() {tkgrab.release(Fen26);tkdestroy(Fen26)})
  tkgrid(tklabel(Fen26,text="",font=Env$police))
  tkgrid(tklabel(Fen26,text="     ",font=Env$police),row=1,column=0)
  tkgrid(rb1,row=1,column=1,columnspan=2,sticky="w")
  tkgrid(rb2,row=2,column=1,columnspan=2,sticky="w")
  tkgrid(tklabel(Fen26,text=paste(var2,"  =  "),font=Env$police),row=2,column=3,sticky="e")
  tkgrid(hor,row=2,column=4,sticky="w")
  tkgrid(rb3,row=3,column=1,columnspan=2,sticky="w")
  tkgrid(tklabel(Fen26,text=paste(var1,"  =  "),font=Env$police),row=3,column=3,sticky="e")
  tkgrid(ver,row=3,column=4,sticky="w")
  tkgrid(rb4,row=4,column=1,columnspan=2,sticky="w")
  tkgrid(tklabel(Fen26,text=paste(var2,"  =  "),font=Env$police),row=4,column=3,sticky="e")
  tkgrid(coeffa,row=4,column=4,sticky="w")
  tkgrid(tklabel(Fen26,text=paste("",var1,"  +  "),font=Env$police),row=4,column=5,sticky="w")
  tkgrid(coeffb,row=4,column=6,sticky="w")
  tkgrid(tklabel(Fen26,text="       ",font=Env$police),row=1,column=7)
  tkgrid(rb5,row=5,column=1,columnspan=6,sticky="w")
  tkgrid(rb8,row=6,column=2,columnspan=5,sticky="w")
  tkgrid(rb9,row=7,column=2,columnspan=5,sticky="w")
  tkgrid(rb6,row=8,column=1,columnspan=6,sticky="w")
  tkgrid(rb7,row=9,column=1,columnspan=6,sticky="w")
  tkgrid(tklabel(Fen26,text=" ",font=Env$police))
  tkgrid(tklabel(Fen26,text=Env$vocab[74,1],font=Env$police),row=11,column=1,sticky="e")
  tkgrid(trait.choose,row=11,column=2,columnspan=2,sticky="w")
  tkgrid(tklabel(Fen26,text=Env$vocab[78,1],font=Env$police),row=12,column=1,sticky="e")
  tkgrid(ep.choose,row=12,column=2,columnspan=2,sticky="w")
  tkgrid(tklabel(Fen26,text="",font=Env$police))
  tkgrid(ok,row=14,column=1,columnspan=3)
  tkgrid(annuler,row=14,column=4,columnspan=3)
  tkgrid(tklabel(Fen26,text="",font=tkfont.create(family="Arial",size=4)))
}

